# Simple Neural Network (Multilayer Perceptron)

In [73]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim
import copy
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import mlflow

In [74]:
train_df = pd.read_csv('../train_competition_2026.csv')
train_df.head()

,obs,sub_id,time,num_0,num_1,num_2,cat_0,cat_1,cat_2,cat_3,cat_4,t_0,t_1,t_2,t_3,t_4,y_1,y_2
0,0,0,2068-09-19 23:34:11,1.38,49,7,1,3,1,0,1,105.5,95.0,67.4,36.6,23.2,33.4,107.4
1,0,0,2068-09-19 23:35:11,1.38,49,7,1,3,1,0,1,104.4,95.0,66.4,37.8,22.7,33.4,107.4
2,0,0,2068-09-19 23:36:11,1.38,49,7,1,3,1,0,1,104.0,95.0,65.2,37.0,22.1,33.4,107.4
3,0,0,2068-09-19 23:37:11,1.38,49,7,1,3,1,0,1,102.8,95.0,63.4,35.9,20.7,33.4,107.4
4,0,0,2068-09-19 23:38:11,1.38,49,7,1,3,1,0,1,101.3,95.1,59.1,34.5,18.1,33.4,107.4

In [75]:
train_df['time'] = pd.to_datetime(train_df['time'], format='%Y-%m-%d %H:%M:%S')

In [76]:
test_df = pd.read_csv('../test_no_outcome.csv')
test_df.head()

,obs,sub_id,time,num_0,num_1,num_2,cat_0,cat_1,cat_2,cat_3,cat_4,t_0,t_1,t_2,t_3,t_4
0,18,1,2134-04-01 22:23:14,-1.0,38,1,1,1,0,0,0,105.4,99.8,50.7,61.4,36.8
1,18,1,2134-04-01 22:24:14,-1.0,38,1,1,1,0,0,0,105.4,99.4,49.4,61.1,36.2
2,18,1,2134-04-01 22:25:14,-1.0,38,1,1,1,0,0,0,104.6,99.0,49.7,61.4,36.6
3,18,1,2134-04-01 22:26:14,-1.0,38,1,1,1,0,0,0,104.5,99.6,51.7,61.8,37.2
4,18,1,2134-04-01 22:27:14,-1.0,38,1,1,1,0,0,0,104.6,99.5,52.5,61.9,37.5

## MLP with PCA

In [77]:
def flatten_blocks(df, feature_cols):
    X_flat = df.groupby(["obs"])[feature_cols].apply(lambda block: block.values.flatten())
    X_flat = pd.DataFrame(X_flat.tolist(), index=X_flat.index)
    return X_flat.reset_index()

In [78]:
feature_cols = [c for c in train_df.columns if c not in ["sub_id", "obs", "time", "y_1", "y_2"]]

X_train_flat = flatten_blocks(train_df, feature_cols)
X_test_flat  = flatten_blocks(test_df, feature_cols)

In [79]:
X_train_flat.head()

,obs,0,1,2,3,4,5,6,7,8,...,380,381,382,383,384,385,386,387,388,389
0,0,1.38,49.0,7.0,1.0,3.0,1.0,0.0,1.0,105.5,...,1.0,3.0,1.0,0.0,1.0,94.5,93.8,59.8,34.3,17.7
1,1,1.38,49.0,7.0,1.0,3.0,1.0,0.0,1.0,98.6,...,1.0,3.0,1.0,0.0,1.0,95.3,92.9,52.1,38.0,22.0
2,2,1.38,49.0,7.0,1.0,3.0,1.0,0.0,1.0,93.1,...,1.0,3.0,1.0,0.0,1.0,91.2,93.4,52.5,36.1,19.1
3,3,1.38,49.0,7.0,1.0,3.0,1.0,0.0,1.0,85.1,...,1.0,3.0,1.0,0.0,1.0,87.1,95.0,61.8,36.4,20.8
4,4,1.38,49.0,7.0,1.0,3.0,1.0,0.0,1.0,88.7,...,1.0,3.0,1.0,0.0,1.0,86.1,89.6,66.7,32.5,17.8

In [80]:
def extract_targets(df):
    return df.groupby(["obs"])[["y_1", "y_2"]].first().reset_index(drop=True)

y_train = extract_targets(train_df)

In [81]:
class SimpleMLP(nn.Module):
    def __init__(self, input_dim, output_dim, num_layers=1, hidden_size=32, dropout=0.0):
        super().__init__()
        
        layers = []
        
        # Input layer
        layers.append(nn.Linear(input_dim, hidden_size))
        layers.append(nn.ReLU())
        if dropout > 0:
            layers.append(nn.Dropout(dropout))
        
        # Hidden layers
        for _ in range(num_layers - 1):
            layers.append(nn.Linear(hidden_size, hidden_size))
            layers.append(nn.ReLU())
            if dropout > 0:
                layers.append(nn.Dropout(dropout))
        
        # Output layer
        layers.append(nn.Linear(hidden_size, output_dim))
        
        self.model = nn.Sequential(*layers)

    def forward(self, x):
        return self.model(x)

In [82]:
def train_mlp(
    X_train, y_train, X_val, y_val,
    input_dim, output_dim, num_layers=1,
    hidden_size=32, dropout=0.0, weight_decay=1e-4,
    epochs=500, epoch_int=10, patience=20, lr=1e-3,
):
    
    model = SimpleMLP(
        input_dim=input_dim,
        output_dim=output_dim,
        num_layers=num_layers,
        hidden_size=hidden_size,
        dropout=dropout
    ).to("cpu")

    param_count = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f'Training model with {param_count} params on {len(X_train)} samples: 1 to {len(X_train)/param_count} param to data ratio')
    criterion = nn.MSELoss()  # change for classification if needed
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)

    # Convert to tensors
    X_train = torch.tensor(X_train, dtype=torch.float32).to("cpu")
    y_train = torch.tensor(y_train, dtype=torch.float32).to("cpu")
    X_val   = torch.tensor(X_val, dtype=torch.float32).to("cpu")
    y_val   = torch.tensor(y_val, dtype=torch.float32).to("cpu")

    best_val_loss = float("inf")
    best_weights = copy.deepcopy(model.state_dict())
    patience_counter = 0

    for epoch in range(epochs):
        # Train
        model.train()
        optimizer.zero_grad()

        train_pred = model(X_train)
        train_loss = criterion(train_pred, y_train)

        train_loss.backward()
        optimizer.step()

        # Val
        model.eval()
        with torch.no_grad():
            val_pred = model(X_val)
            val_loss = criterion(val_pred, y_val)
            
            # Calc r2
            train_r2 = r2_score(y_train.cpu().numpy(), train_pred.detach().cpu().numpy())
            val_r2 = r2_score(y_val.cpu().numpy(), val_pred.cpu().numpy())

        if epoch % epoch_int == 0:
            print(f'Epoch {epoch:03d} | '
                f'Train Loss: {train_loss.item():.4f} | Val Loss {val_loss.item():.4f} | '
                f'Train R2: {train_r2:.4f} | Val R2 {val_r2:.4f}')

        # Early stopping
        if val_loss.item() < best_val_loss:
            best_val_loss = val_loss.item()
            best_weights = copy.deepcopy(model.state_dict())
            patience_counter = 0
        else:
            patience_counter += 1

        if patience_counter >= patience:
            print(f"Early stopping at epoch {epoch}")
            break

    # Restore best model
    model.load_state_dict(best_weights)
    model.eval()
    with torch.no_grad():
        final_val_pred = model(X_val)
        final_val_loss = criterion(final_val_pred, y_val)
        print(f'Final val loss: {final_val_loss:.4f}')

    return model, final_val_loss

In [83]:
def run_pipeline(hp):
    k = hp['pca_k']
    
    scaler_x = StandardScaler()
    X_train_raw = X_train_flat.drop(columns=["obs"])
    
    X_train_scaled = scaler_x.fit_transform(X_train_raw)

    pca = PCA(n_components=k, random_state=42)
    X_train_pca = pca.fit_transform(X_train_scaled)
    
    scaler_y = StandardScaler()
    y_train_scaled = scaler_y.fit_transform(y_train)

    X_train_split, X_val, y_train_split, y_val = train_test_split(
        X_train_pca, y_train_scaled, test_size=0.2, random_state=42
    )

    model, val_loss = train_mlp(
        X_train_split, y_train_split, X_val, y_val,
        input_dim=X_train_split.shape[1],
        output_dim=2,
        num_layers=hp['num_layers'],
        hidden_size=hp['hidden_size'],
        dropout=hp['dropout'],
        weight_decay=hp['weight_decay'],
        epochs=hp['epochs'],
        epoch_int=hp['epoch_int'],
        patience=hp['patience'],
        lr=hp['lr']
    )
    
    return model, val_loss, scaler_x, scaler_y, pca

In [84]:
hp = {
    'pca_k': 100,
    'hidden_size': 128,
    'num_layers': 4,
    'dropout': 0.0,
    'weight_decay': 1e-3,
    'epochs': 10000, 
    'epoch_int': 50,
    'patience': 50,
    'lr': 1e-3
}

model, val_loss, scaler_x, scaler_y, pca = run_pipeline(hp)

Training model with 62722 params on 11536 samples: 1 to 0.18392270654634738 param to data ratio
Epoch 000 | Train Loss: 1.0094 | Val Loss 0.9525 | Train R2: -0.0043 | Val R2 0.0273
Epoch 050 | Train Loss: 0.1949 | Val Loss 0.1984 | Train R2: 0.8058 | Val R2 0.7984
Epoch 100 | Train Loss: 0.1779 | Val Loss 0.1934 | Train R2: 0.8228 | Val R2 0.8035
Epoch 150 | Train Loss: 0.1616 | Val Loss 0.1965 | Train R2: 0.8390 | Val R2 0.8004
Early stopping at epoch 158
Final val loss: 0.1934

In [85]:
def get_real_predictions(model, X_test_df, scaler_x, scaler_y, pca):
    X_raw = X_test_df.drop(columns=["obs"]) if "obs" in X_test_df.columns else X_test_df
    X_scaled = scaler_x.transform(X_raw)
    
    X_pca = pca.transform(X_scaled)
    
    model.eval()
    X_tensor = torch.FloatTensor(X_pca)
    
    with torch.no_grad():
        y_pred_tensor = model(X_tensor)

    y_pred_scaled = y_pred_tensor.cpu().numpy()
    y_pred_final = scaler_y.inverse_transform(y_pred_scaled)
    
    return y_pred_final

In [86]:
predictions = get_real_predictions(model, X_test_flat, scaler_x, scaler_y, pca)

y_test_pred = get_real_predictions(model, X_test_flat, scaler_x, scaler_y, pca)

pred_df = pd.concat(
    [
        X_test_flat[["obs"]].reset_index(drop=True), 
        pd.DataFrame(y_test_pred, columns=["y_1", "y_2"])
    ],
    axis=1
)

len(y_test_pred)

3450

## MLP with Aggregated Features

In [105]:
def slope(values):
    x = np.arange(len(values)).reshape(-1, 1)
    return LinearRegression().fit(x, values).coef_[0]

def collapse_obs(df, feature_cols):
    
    def aggregate_group(group):
        group = group.sort_values("time")
        features = {}
        
        for col in feature_cols:
            vals = group[col].values
            
            features[f"{col}_min"] = np.min(vals)
            features[f"{col}_max"] = np.max(vals)
            features[f"{col}_mean"] = np.mean(vals)
            features[f"{col}_std"] = np.std(vals)
            
            features[f"{col}_first"] = vals[0]
            features[f"{col}_last"] = vals[-1]
            features[f"{col}_delta"] = vals[-1] - vals[0]
            features[f"{col}_slope"] = slope(vals)
        
        return pd.Series(features)

    X = (
        df
        .groupby("obs", group_keys=False)
        .apply(aggregate_group, include_groups=False)
        .reset_index()
    )
    
    return X

In [106]:
def collapse_target(df):
    y = (
        df
        .groupby(["obs"])[["y_1", "y_2"]]
        .first()
        .reset_index(drop=True)
    )
    return y

In [107]:
feature_cols = [
    c for c in train_df.columns
    if c not in ["obs", "sub_id", "time", "y_1", "y_2"]
]

X_train = collapse_obs(train_df, feature_cols).drop(columns=['obs'])
y_train = collapse_target(train_df)

X_test = collapse_obs(test_df, feature_cols)
test_index = X_test[["obs"]].copy()
X_test = X_test.drop(columns=['obs'])

In [108]:
X_train.head()

,num_0_min,num_0_max,num_0_mean,num_0_std,num_0_first,num_0_last,num_0_delta,num_0_slope,num_1_min,num_1_max,...,t_3_delta,t_3_slope,t_4_min,t_4_max,t_4_mean,t_4_std,t_4_first,t_4_last,t_4_delta,t_4_slope
0,1.38,1.38,1.38,4.440892e-16,1.38,1.38,0.0,4.611663e-33,49.0,49.0,...,-2.3,0.013415,14.3,28.8,21.880000,3.210234,23.2,17.7,-5.5,0.032392
1,1.38,1.38,1.38,4.440892e-16,1.38,1.38,0.0,4.611663e-33,49.0,49.0,...,0.3,-0.036129,19.8,30.3,24.026667,2.722001,19.8,22.0,2.2,0.011791
2,1.38,1.38,1.38,4.440892e-16,1.38,1.38,0.0,4.611663e-33,49.0,49.0,...,-3.3,-0.156196,17.5,29.0,21.453333,2.955417,24.4,19.1,-5.3,-0.259043
3,1.38,1.38,1.38,4.440892e-16,1.38,1.38,0.0,4.611663e-33,49.0,49.0,...,1.6,0.054683,17.4,27.8,20.696667,1.896046,19.3,20.8,1.5,0.078109
4,1.38,1.38,1.38,4.440892e-16,1.38,1.38,0.0,4.611663e-33,49.0,49.0,...,-3.8,-0.051880,17.8,25.0,21.500000,1.444761,21.8,17.8,-4.0,-0.014194

In [109]:
def extract_targets(df):
    return df.groupby(["obs"])[["y_1", "y_2"]].first().reset_index(drop=True)

y_train = extract_targets(train_df)

In [110]:
def run_pipeline(hp):
    scaler_x = StandardScaler()
    
    X_train_scaled = scaler_x.fit_transform(X_train)
    
    scaler_y = StandardScaler()
    y_train_scaled = scaler_y.fit_transform(y_train)

    X_train_split, X_val, y_train_split, y_val = train_test_split(
        X_train_scaled, y_train_scaled, test_size=0.2, random_state=42
    )

    model, val_loss = train_mlp(
        X_train_split, y_train_split, X_val, y_val,
        input_dim=X_train_split.shape[1],
        output_dim=2,
        num_layers=hp['num_layers'],
        hidden_size=hp['hidden_size'],
        dropout=hp['dropout'],
        weight_decay=hp['weight_decay'],
        epochs=hp['epochs'],
        epoch_int=hp['epoch_int'],
        patience=hp['patience'],
        lr=hp['lr']
    )
    
    return model, val_loss, scaler_x, scaler_y

In [114]:
hp = {
    'hidden_size': 256,
    'num_layers': 2,
    'dropout': 0.4,
    'weight_decay': 1e-3,
    'epochs': 10000, 
    'epoch_int': 50,
    'patience': 50,
    'lr': 5e-3
}

model, val_loss, scaler_x, scaler_y = run_pipeline(hp)

Training model with 93186 params on 11536 samples: 1 to 0.12379541991286244 param to data ratio
Epoch 000 | Train Loss: 1.0143 | Val Loss 0.5776 | Train R2: -0.0092 | Val R2 0.4095
Epoch 050 | Train Loss: 0.2169 | Val Loss 0.1929 | Train R2: 0.7839 | Val R2 0.8040
Epoch 100 | Train Loss: 0.2055 | Val Loss 0.1902 | Train R2: 0.7953 | Val R2 0.8068
Epoch 150 | Train Loss: 0.1999 | Val Loss 0.1908 | Train R2: 0.8008 | Val R2 0.8062
Early stopping at epoch 154
Final val loss: 0.1898

In [115]:
def get_real_predictions(model, X_test_df, scaler_x, scaler_y):
    X_raw = X_test_df.drop(columns=["obs"]) if "obs" in X_test_df.columns else X_test_df
    X_scaled = scaler_x.transform(X_raw)
    
    model.eval()
    X_tensor = torch.FloatTensor(X_scaled)
    
    with torch.no_grad():
        y_pred_tensor = model(X_tensor)

    y_pred_scaled = y_pred_tensor.cpu().numpy()
    y_pred_final = scaler_y.inverse_transform(y_pred_scaled)
    
    return y_pred_final

In [116]:
predictions = get_real_predictions(model, X_test, scaler_x, scaler_y)

y_test_pred = get_real_predictions(model, X_test, scaler_x, scaler_y)

pred_df = pd.concat(
    [
        X_test_flat[["obs"]].reset_index(drop=True), 
        pd.DataFrame(y_test_pred, columns=["y_1", "y_2"])
    ],
    axis=1
)

len(y_test_pred)

3450

## Saving and MLFlow

In [118]:
pred_df.to_csv("mlp_agg_1.csv", index=False)

In [113]:
def run_with_mlflow(hp):
    run_name = f"lstm_h{hp['hidden_size']}_l{hp['num_layers']}_d{hp['dropout']}_w{hp['weight_decay']}"
    with mlflow.start_run(run_name=run_name):
        mlflow.set_tag("grid_search", "agg_stats_mlp")
        mlflow.log_params(hp)
        model, val_loss, _, _ = run_pipeline(hp)
        mlflow.log_metric("val_loss", val_loss)
        
        return model, val_loss

if __name__ == '__main__':
    db_path = "/Users/connoryablonski/Dropbox/USF_MSDS/advanced_ml/mlflow.db"
    mlflow.set_tracking_uri(f"sqlite:///{db_path}")
    mlflow.set_experiment("AML_Project_MLP_Grid_Search")
    
    print(f"Tracking URI: {mlflow.get_tracking_uri()}")
    print(f"Active Experiment: {mlflow.get_experiment_by_name('AML_Project_MLP_Grid_Search').experiment_id}")

    from itertools import product

    best_score = float("inf")
    
    hidden_sizes = [32, 64, 128, 256]
    num_layers = [2, 4, 6, 8]
    dropouts = [0.0, 0.2, 0.4]
    weight_decays = [1e-5, 1e-4, 1e-3]
    
    best_model = None
    # best_pca = None

    for hs, nl, dr, wd in product(hidden_sizes, num_layers, dropouts, weight_decays):
        
        hp = {
            'hidden_size': hs,
            'num_layers': nl,
            'dropout': dr,
            'weight_decay': wd,
            'epochs': 10000, 
            'epoch_int': 50,
            'patience': 50,
            'lr': 5e-3
        }
        
        model, score = run_with_mlflow(hp)
        
        if score < best_score:
            best_score = score
            best_hp = hp
            best_model = model
            
            # best_pca = PCA(n_components=hp['pca_k'], random_state=42)
            # best_pca.fit(X_train_flat.drop(columns=["obs"]))
            

    print(f"Best config: {best_hp}, val_score: {best_score}")

Tracking URI: sqlite:////Users/connoryablonski/Dropbox/USF_MSDS/advanced_ml/mlflow.db
Active Experiment: 1
Training model with 4482 params on 11536 samples: 1 to 2.5738509593931282 param to data ratio
Epoch 000 | Train Loss: 0.9992 | Val Loss 0.9083 | Train R2: 0.0058 | Val R2 0.0720
Epoch 050 | Train Loss: 0.2043 | Val Loss 0.2027 | Train R2: 0.7965 | Val R2 0.7940
Epoch 100 | Train Loss: 0.1916 | Val Loss 0.1958 | Train R2: 0.8091 | Val R2 0.8010
Epoch 150 | Train Loss: 0.1839 | Val Loss 0.1960 | Train R2: 0.8168 | Val R2 0.8009
Early stopping at epoch 180
Final val loss: 0.1955
Training model with 4482 params on 11536 samples: 1 to 2.5738509593931282 param to data ratio
Epoch 000 | Train Loss: 1.0096 | Val Loss 0.9186 | Train R2: -0.0044 | Val R2 0.0615
Epoch 050 | Train Loss: 0.2057 | Val Loss 0.2032 | Train R2: 0.7950 | Val R2 0.7935
Epoch 100 | Train Loss: 0.1920 | Val Loss 0.1967 | Train R2: 0.8087 | Val R2 0.8002
Epoch 150 | Train Loss: 0.1846 | Val Loss 0.1973 | Train R2: 0.8161 | Val R2 0.7996
Early stopping at epoch 158
Final val loss: 0.1964
Training model with 4482 params on 11536 samples: 1 to 2.5738509593931282 param to data ratio
Epoch 000 | Train Loss: 1.0114 | Val Loss 0.9194 | Train R2: -0.0064 | Val R2 0.0611
Epoch 050 | Train Loss: 0.2050 | Val Loss 0.2012 | Train R2: 0.7958 | Val R2 0.7955
Epoch 100 | Train Loss: 0.1924 | Val Loss 0.1949 | Train R2: 0.8083 | Val R2 0.8020
Epoch 150 | Train Loss: 0.1858 | Val Loss 0.1944 | Train R2: 0.8148 | Val R2 0.8025
Early stopping at epoch 173
Final val loss: 0.1943
Training model with 4482 params on 11536 samples: 1 to 2.5738509593931282 param to data ratio
Epoch 000 | Train Loss: 1.0452 | Val Loss 0.9475 | Train R2: -0.0399 | Val R2 0.0321
Epoch 050 | Train Loss: 0.2617 | Val Loss 0.2049 | Train R2: 0.7394 | Val R2 0.7918
Epoch 100 | Train Loss: 0.2479 | Val Loss 0.1982 | Train R2: 0.7531 | Val R2 0.7987
Epoch 150 | Train Loss: 0.2379 | Val Loss 0.1987 | Train R2: 0.7630 | Val R2 0.7982
Early stopping at epoch 195
Final val loss: 0.1965
Training model with 4482 params on 11536 samples: 1 to 2.5738509593931282 param to data ratio
Epoch 000 | Train Loss: 1.0246 | Val Loss 0.9184 | Train R2: -0.0195 | Val R2 0.0620
Epoch 050 | Train Loss: 0.2608 | Val Loss 0.2045 | Train R2: 0.7402 | Val R2 0.7923
Epoch 100 | Train Loss: 0.2429 | Val Loss 0.1966 | Train R2: 0.7581 | Val R2 0.8002
Epoch 150 | Train Loss: 0.2369 | Val Loss 0.1955 | Train R2: 0.7640 | Val R2 0.8013
Epoch 200 | Train Loss: 0.2341 | Val Loss 0.1961 | Train R2: 0.7668 | Val R2 0.8008
Early stopping at epoch 231
Final val loss: 0.1946
Training model with 4482 params on 11536 samples: 1 to 2.5738509593931282 param to data ratio
Epoch 000 | Train Loss: 1.0363 | Val Loss 0.9251 | Train R2: -0.0309 | Val R2 0.0541
Epoch 050 | Train Loss: 0.2641 | Val Loss 0.2069 | Train R2: 0.7369 | Val R2 0.7898
Epoch 100 | Train Loss: 0.2489 | Val Loss 0.1976 | Train R2: 0.7520 | Val R2 0.7993
Epoch 150 | Train Loss: 0.2382 | Val Loss 0.1955 | Train R2: 0.7628 | Val R2 0.8014
Epoch 200 | Train Loss: 0.2347 | Val Loss 0.1953 | Train R2: 0.7662 | Val R2 0.8016
Epoch 250 | Train Loss: 0.2344 | Val Loss 0.1956 | Train R2: 0.7665 | Val R2 0.8012
Early stopping at epoch 261
Final val loss: 0.1944
Training model with 4482 params on 11536 samples: 1 to 2.5738509593931282 param to data ratio
Epoch 000 | Train Loss: 1.0367 | Val Loss 0.9452 | Train R2: -0.0313 | Val R2 0.0342
Epoch 050 | Train Loss: 0.3331 | Val Loss 0.2215 | Train R2: 0.6682 | Val R2 0.7750
Epoch 100 | Train Loss: 0.3056 | Val Loss 0.2143 | Train R2: 0.6957 | Val R2 0.7822
Early stopping at epoch 144
Final val loss: 0.2095
Training model with 4482 params on 11536 samples: 1 to 2.5738509593931282 param to data ratio
Epoch 000 | Train Loss: 1.0490 | Val Loss 0.9258 | Train R2: -0.0437 | Val R2 0.0545
Epoch 050 | Train Loss: 0.3285 | Val Loss 0.2203 | Train R2: 0.6729 | Val R2 0.7761
Epoch 100 | Train Loss: 0.3060 | Val Loss 0.2106 | Train R2: 0.6952 | Val R2 0.7859
Epoch 150 | Train Loss: 0.3012 | Val Loss 0.2077 | Train R2: 0.7000 | Val R2 0.7889
Early stopping at epoch 186
Final val loss: 0.2056
Training model with 4482 params on 11536 samples: 1 to 2.5738509593931282 param to data ratio
Epoch 000 | Train Loss: 1.0253 | Val Loss 0.9183 | Train R2: -0.0202 | Val R2 0.0618
Epoch 050 | Train Loss: 0.3283 | Val Loss 0.2168 | Train R2: 0.6731 | Val R2 0.7796
Epoch 100 | Train Loss: 0.3119 | Val Loss 0.2139 | Train R2: 0.6894 | Val R2 0.7827
Epoch 150 | Train Loss: 0.3080 | Val Loss 0.2101 | Train R2: 0.6933 | Val R2 0.7865
Epoch 200 | Train Loss: 0.3000 | Val Loss 0.2117 | Train R2: 0.7012 | Val R2 0.7849
Epoch 250 | Train Loss: 0.2970 | Val Loss 0.2091 | Train R2: 0.7042 | Val R2 0.7875
Early stopping at epoch 275
Final val loss: 0.2078
Training model with 6594 params on 11536 samples: 1 to 1.7494692144373674 param to data ratio
Epoch 000 | Train Loss: 1.0075 | Val Loss 0.9688 | Train R2: -0.0025 | Val R2 0.0107
Epoch 050 | Train Loss: 0.2056 | Val Loss 0.2037 | Train R2: 0.7951 | Val R2 0.7930
Epoch 100 | Train Loss: 0.1904 | Val Loss 0.1966 | Train R2: 0.8103 | Val R2 0.8003
Epoch 150 | Train Loss: 0.1830 | Val Loss 0.1973 | Train R2: 0.8177 | Val R2 0.7996
Early stopping at epoch 156
Final val loss: 0.1963
Training model with 6594 params on 11536 samples: 1 to 1.7494692144373674 param to data ratio
Epoch 000 | Train Loss: 1.0058 | Val Loss 0.9702 | Train R2: -0.0007 | Val R2 0.0093
Epoch 050 | Train Loss: 0.2076 | Val Loss 0.2037 | Train R2: 0.7931 | Val R2 0.7930
Epoch 100 | Train Loss: 0.1929 | Val Loss 0.1960 | Train R2: 0.8078 | Val R2 0.8009
Epoch 150 | Train Loss: 0.1855 | Val Loss 0.1958 | Train R2: 0.8152 | Val R2 0.8011
Early stopping at epoch 173
Final val loss: 0.1955
Training model with 6594 params on 11536 samples: 1 to 1.7494692144373674 param to data ratio
Epoch 000 | Train Loss: 1.0234 | Val Loss 0.9850 | Train R2: -0.0182 | Val R2 -0.0059
Epoch 050 | Train Loss: 0.2089 | Val Loss 0.2037 | Train R2: 0.7919 | Val R2 0.7931
Epoch 100 | Train Loss: 0.1953 | Val Loss 0.1949 | Train R2: 0.8054 | Val R2 0.8020
Epoch 150 | Train Loss: 0.1874 | Val Loss 0.1927 | Train R2: 0.8133 | Val R2 0.8042
Epoch 200 | Train Loss: 0.1813 | Val Loss 0.1927 | Train R2: 0.8193 | Val R2 0.8042
Early stopping at epoch 234
Final val loss: 0.1923
Training model with 6594 params on 11536 samples: 1 to 1.7494692144373674 param to data ratio
Epoch 000 | Train Loss: 1.0106 | Val Loss 0.9728 | Train R2: -0.0055 | Val R2 0.0066
Epoch 050 | Train Loss: 0.2984 | Val Loss 0.2118 | Train R2: 0.7028 | Val R2 0.7847
Epoch 100 | Train Loss: 0.2758 | Val Loss 0.2061 | Train R2: 0.7253 | Val R2 0.7906
Epoch 150 | Train Loss: 0.2630 | Val Loss 0.2082 | Train R2: 0.7380 | Val R2 0.7884
Early stopping at epoch 197
Final val loss: 0.2047
Training model with 6594 params on 11536 samples: 1 to 1.7494692144373674 param to data ratio
Epoch 000 | Train Loss: 1.0143 | Val Loss 0.9719 | Train R2: -0.0092 | Val R2 0.0074
Epoch 050 | Train Loss: 0.3061 | Val Loss 0.2119 | Train R2: 0.6951 | Val R2 0.7846
Epoch 100 | Train Loss: 0.2775 | Val Loss 0.2036 | Train R2: 0.7236 | Val R2 0.7931
Epoch 150 | Train Loss: 0.2655 | Val Loss 0.2014 | Train R2: 0.7356 | Val R2 0.7953
Epoch 200 | Train Loss: 0.2558 | Val Loss 0.2015 | Train R2: 0.7453 | Val R2 0.7952
Epoch 250 | Train Loss: 0.2534 | Val Loss 0.2015 | Train R2: 0.7476 | Val R2 0.7952
Early stopping at epoch 282
Final val loss: 0.1998
Training model with 6594 params on 11536 samples: 1 to 1.7494692144373674 param to data ratio
Epoch 000 | Train Loss: 1.0218 | Val Loss 0.9717 | Train R2: -0.0167 | Val R2 0.0077
Epoch 050 | Train Loss: 0.3012 | Val Loss 0.2127 | Train R2: 0.7000 | Val R2 0.7839
Epoch 100 | Train Loss: 0.2724 | Val Loss 0.2036 | Train R2: 0.7287 | Val R2 0.7931
Epoch 150 | Train Loss: 0.2655 | Val Loss 0.2011 | Train R2: 0.7356 | Val R2 0.7956
Epoch 200 | Train Loss: 0.2635 | Val Loss 0.1973 | Train R2: 0.7376 | Val R2 0.7995
Epoch 250 | Train Loss: 0.2546 | Val Loss 0.1996 | Train R2: 0.7464 | Val R2 0.7972
Early stopping at epoch 250
Final val loss: 0.1973
Training model with 6594 params on 11536 samples: 1 to 1.7494692144373674 param to data ratio
Epoch 000 | Train Loss: 1.0120 | Val Loss 0.9675 | Train R2: -0.0069 | Val R2 0.0119
Epoch 050 | Train Loss: 0.4266 | Val Loss 0.2825 | Train R2: 0.5752 | Val R2 0.7127
Epoch 100 | Train Loss: 0.3872 | Val Loss 0.2484 | Train R2: 0.6145 | Val R2 0.7473
Epoch 150 | Train Loss: 0.3552 | Val Loss 0.2395 | Train R2: 0.6463 | Val R2 0.7563
Early stopping at epoch 169
Final val loss: 0.2390
Training model with 6594 params on 11536 samples: 1 to 1.7494692144373674 param to data ratio
Epoch 000 | Train Loss: 1.0141 | Val Loss 0.9670 | Train R2: -0.0090 | Val R2 0.0127
Epoch 050 | Train Loss: 0.4026 | Val Loss 0.2567 | Train R2: 0.5991 | Val R2 0.7389
Epoch 100 | Train Loss: 0.3633 | Val Loss 0.2299 | Train R2: 0.6383 | Val R2 0.7663
Epoch 150 | Train Loss: 0.3441 | Val Loss 0.2241 | Train R2: 0.6573 | Val R2 0.7721
Early stopping at epoch 176
Final val loss: 0.2206
Training model with 6594 params on 11536 samples: 1 to 1.7494692144373674 param to data ratio
Epoch 000 | Train Loss: 1.0118 | Val Loss 0.9611 | Train R2: -0.0067 | Val R2 0.0186
Epoch 050 | Train Loss: 0.4067 | Val Loss 0.2589 | Train R2: 0.5951 | Val R2 0.7368
Epoch 100 | Train Loss: 0.3724 | Val Loss 0.2370 | Train R2: 0.6292 | Val R2 0.7590
Epoch 150 | Train Loss: 0.3537 | Val Loss 0.2285 | Train R2: 0.6478 | Val R2 0.7677
Epoch 200 | Train Loss: 0.3507 | Val Loss 0.2312 | Train R2: 0.6508 | Val R2 0.7649
Early stopping at epoch 246
Final val loss: 0.2215
Training model with 8706 params on 11536 samples: 1 to 1.325063174821962 param to data ratio
Epoch 000 | Train Loss: 1.0057 | Val Loss 0.9757 | Train R2: -0.0006 | Val R2 0.0037
Epoch 050 | Train Loss: 0.2143 | Val Loss 0.2082 | Train R2: 0.7865 | Val R2 0.7885
Epoch 100 | Train Loss: 0.1958 | Val Loss 0.1962 | Train R2: 0.8048 | Val R2 0.8007
Epoch 150 | Train Loss: 0.1874 | Val Loss 0.1934 | Train R2: 0.8132 | Val R2 0.8035
Early stopping at epoch 194
Final val loss: 0.1933
Training model with 8706 params on 11536 samples: 1 to 1.325063174821962 param to data ratio
Epoch 000 | Train Loss: 1.0245 | Val Loss 0.9827 | Train R2: -0.0194 | Val R2 -0.0035
Epoch 050 | Train Loss: 0.2146 | Val Loss 0.2116 | Train R2: 0.7862 | Val R2 0.7849
Epoch 100 | Train Loss: 0.1983 | Val Loss 0.1964 | Train R2: 0.8023 | Val R2 0.8005
Epoch 150 | Train Loss: 0.1893 | Val Loss 0.1939 | Train R2: 0.8113 | Val R2 0.8030
Epoch 200 | Train Loss: 0.1818 | Val Loss 0.1959 | Train R2: 0.8189 | Val R2 0.8010
Early stopping at epoch 220
Final val loss: 0.1937
Training model with 8706 params on 11536 samples: 1 to 1.325063174821962 param to data ratio
Epoch 000 | Train Loss: 1.0143 | Val Loss 0.9829 | Train R2: -0.0091 | Val R2 -0.0037
Epoch 050 | Train Loss: 0.2118 | Val Loss 0.2049 | Train R2: 0.7890 | Val R2 0.7919
Epoch 100 | Train Loss: 0.1932 | Val Loss 0.1931 | Train R2: 0.8075 | Val R2 0.8038
Epoch 150 | Train Loss: 0.1860 | Val Loss 0.1927 | Train R2: 0.8146 | Val R2 0.8042
Early stopping at epoch 196
Final val loss: 0.1924
Training model with 8706 params on 11536 samples: 1 to 1.325063174821962 param to data ratio
Epoch 000 | Train Loss: 1.0105 | Val Loss 0.9837 | Train R2: -0.0055 | Val R2 -0.0044
Epoch 050 | Train Loss: 0.3557 | Val Loss 0.2319 | Train R2: 0.6458 | Val R2 0.7642
Epoch 100 | Train Loss: 0.3034 | Val Loss 0.2137 | Train R2: 0.6978 | Val R2 0.7828
Epoch 150 | Train Loss: 0.2876 | Val Loss 0.2139 | Train R2: 0.7135 | Val R2 0.7826
Early stopping at epoch 165
Final val loss: 0.2096
Training model with 8706 params on 11536 samples: 1 to 1.325063174821962 param to data ratio
Epoch 000 | Train Loss: 1.0142 | Val Loss 0.9794 | Train R2: -0.0091 | Val R2 -0.0002
Epoch 050 | Train Loss: 0.3671 | Val Loss 0.2381 | Train R2: 0.6345 | Val R2 0.7578
Epoch 100 | Train Loss: 0.3070 | Val Loss 0.2237 | Train R2: 0.6943 | Val R2 0.7724
Epoch 150 | Train Loss: 0.2880 | Val Loss 0.2155 | Train R2: 0.7133 | Val R2 0.7808
Epoch 200 | Train Loss: 0.2784 | Val Loss 0.2170 | Train R2: 0.7228 | Val R2 0.7793
Early stopping at epoch 239
Final val loss: 0.2138
Training model with 8706 params on 11536 samples: 1 to 1.325063174821962 param to data ratio
Epoch 000 | Train Loss: 1.0311 | Val Loss 0.9859 | Train R2: -0.0260 | Val R2 -0.0067
Epoch 050 | Train Loss: 0.3598 | Val Loss 0.2324 | Train R2: 0.6417 | Val R2 0.7637
Epoch 100 | Train Loss: 0.3023 | Val Loss 0.2124 | Train R2: 0.6990 | Val R2 0.7841
Epoch 150 | Train Loss: 0.2869 | Val Loss 0.2066 | Train R2: 0.7143 | Val R2 0.7900
Epoch 200 | Train Loss: 0.2855 | Val Loss 0.2080 | Train R2: 0.7156 | Val R2 0.7886
Early stopping at epoch 213
Final val loss: 0.2054
Training model with 8706 params on 11536 samples: 1 to 1.325063174821962 param to data ratio
Epoch 000 | Train Loss: 1.0126 | Val Loss 0.9776 | Train R2: -0.0075 | Val R2 0.0017
Epoch 050 | Train Loss: 0.5281 | Val Loss 0.4140 | Train R2: 0.4742 | Val R2 0.5793
Epoch 100 | Train Loss: 0.4389 | Val Loss 0.3338 | Train R2: 0.5630 | Val R2 0.6607
Epoch 150 | Train Loss: 0.4164 | Val Loss 0.3076 | Train R2: 0.5854 | Val R2 0.6873
Epoch 200 | Train Loss: 0.3991 | Val Loss 0.3110 | Train R2: 0.6026 | Val R2 0.6839
Epoch 250 | Train Loss: 0.3841 | Val Loss 0.2920 | Train R2: 0.6176 | Val R2 0.7032
Epoch 300 | Train Loss: 0.3813 | Val Loss 0.2867 | Train R2: 0.6203 | Val R2 0.7085
Epoch 350 | Train Loss: 0.3758 | Val Loss 0.2850 | Train R2: 0.6258 | Val R2 0.7104
Epoch 400 | Train Loss: 0.3689 | Val Loss 0.2811 | Train R2: 0.6327 | Val R2 0.7143
Early stopping at epoch 424
Final val loss: 0.2650
Training model with 8706 params on 11536 samples: 1 to 1.325063174821962 param to data ratio
Epoch 000 | Train Loss: 1.0182 | Val Loss 0.9902 | Train R2: -0.0131 | Val R2 -0.0110
Epoch 050 | Train Loss: 0.4804 | Val Loss 0.3213 | Train R2: 0.5218 | Val R2 0.6728
Epoch 100 | Train Loss: 0.4250 | Val Loss 0.2773 | Train R2: 0.5769 | Val R2 0.7179
Epoch 150 | Train Loss: 0.4085 | Val Loss 0.2633 | Train R2: 0.5933 | Val R2 0.7321
Epoch 200 | Train Loss: 0.3903 | Val Loss 0.2512 | Train R2: 0.6114 | Val R2 0.7444
Early stopping at epoch 244
Final val loss: 0.2452
Training model with 8706 params on 11536 samples: 1 to 1.325063174821962 param to data ratio
Epoch 000 | Train Loss: 1.0230 | Val Loss 0.9856 | Train R2: -0.0179 | Val R2 -0.0065
Epoch 050 | Train Loss: 0.4805 | Val Loss 0.3083 | Train R2: 0.5216 | Val R2 0.6865
Epoch 100 | Train Loss: 0.4284 | Val Loss 0.2792 | Train R2: 0.5735 | Val R2 0.7160
Epoch 150 | Train Loss: 0.4245 | Val Loss 0.2714 | Train R2: 0.5774 | Val R2 0.7238
Epoch 200 | Train Loss: 0.3975 | Val Loss 0.2571 | Train R2: 0.6043 | Val R2 0.7384
Epoch 250 | Train Loss: 0.3801 | Val Loss 0.2518 | Train R2: 0.6216 | Val R2 0.7438
Epoch 300 | Train Loss: 0.3789 | Val Loss 0.2468 | Train R2: 0.6228 | Val R2 0.7489
Epoch 350 | Train Loss: 0.3680 | Val Loss 0.2404 | Train R2: 0.6336 | Val R2 0.7554
Early stopping at epoch 374
Final val loss: 0.2362
Training model with 10818 params on 11536 samples: 1 to 1.066370863375855 param to data ratio
Epoch 000 | Train Loss: 1.0195 | Val Loss 0.9848 | Train R2: -0.0143 | Val R2 -0.0056
Epoch 050 | Train Loss: 0.5475 | Val Loss 0.5330 | Train R2: 0.4541 | Val R2 0.4603
Epoch 100 | Train Loss: 0.2075 | Val Loss 0.2039 | Train R2: 0.7932 | Val R2 0.7929
Epoch 150 | Train Loss: 0.1931 | Val Loss 0.1999 | Train R2: 0.8075 | Val R2 0.7969
Epoch 200 | Train Loss: 0.1842 | Val Loss 0.2018 | Train R2: 0.8165 | Val R2 0.7951
Early stopping at epoch 211
Final val loss: 0.1984
Training model with 10818 params on 11536 samples: 1 to 1.066370863375855 param to data ratio
Epoch 000 | Train Loss: 1.0055 | Val Loss 0.9795 | Train R2: -0.0004 | Val R2 -0.0002
Epoch 050 | Train Loss: 0.5448 | Val Loss 0.5312 | Train R2: 0.4569 | Val R2 0.4619
Epoch 100 | Train Loss: 0.2227 | Val Loss 0.2159 | Train R2: 0.7782 | Val R2 0.7806
Epoch 150 | Train Loss: 0.2060 | Val Loss 0.2029 | Train R2: 0.7947 | Val R2 0.7939
Epoch 200 | Train Loss: 0.1852 | Val Loss 0.1964 | Train R2: 0.8155 | Val R2 0.8004
Early stopping at epoch 231
Final val loss: 0.1960
Training model with 10818 params on 11536 samples: 1 to 1.066370863375855 param to data ratio
Epoch 000 | Train Loss: 1.0278 | Val Loss 0.9892 | Train R2: -0.0227 | Val R2 -0.0101
Epoch 050 | Train Loss: 0.5695 | Val Loss 0.5427 | Train R2: 0.4329 | Val R2 0.4478
Epoch 100 | Train Loss: 0.3632 | Val Loss 0.3330 | Train R2: 0.6379 | Val R2 0.6621
Epoch 150 | Train Loss: 0.1990 | Val Loss 0.1990 | Train R2: 0.8017 | Val R2 0.7978
Epoch 200 | Train Loss: 0.1953 | Val Loss 0.1990 | Train R2: 0.8054 | Val R2 0.7978
Early stopping at epoch 240
Final val loss: 0.1948
Training model with 10818 params on 11536 samples: 1 to 1.066370863375855 param to data ratio
Epoch 000 | Train Loss: 1.0137 | Val Loss 0.9846 | Train R2: -0.0086 | Val R2 -0.0055
Epoch 050 | Train Loss: 0.6265 | Val Loss 0.5743 | Train R2: 0.3772 | Val R2 0.4121
Epoch 100 | Train Loss: 0.3901 | Val Loss 0.2757 | Train R2: 0.6116 | Val R2 0.7195
Epoch 150 | Train Loss: 0.3280 | Val Loss 0.2698 | Train R2: 0.6734 | Val R2 0.7257
Epoch 200 | Train Loss: 0.3132 | Val Loss 0.2632 | Train R2: 0.6881 | Val R2 0.7324
Early stopping at epoch 206
Final val loss: 0.2496
Training model with 10818 params on 11536 samples: 1 to 1.066370863375855 param to data ratio
Epoch 000 | Train Loss: 1.0259 | Val Loss 0.9920 | Train R2: -0.0207 | Val R2 -0.0132
Epoch 050 | Train Loss: 0.5935 | Val Loss 0.5331 | Train R2: 0.4088 | Val R2 0.4588
Epoch 100 | Train Loss: 0.3830 | Val Loss 0.2719 | Train R2: 0.6187 | Val R2 0.7236
Epoch 150 | Train Loss: 0.3208 | Val Loss 0.2268 | Train R2: 0.6805 | Val R2 0.7695
Epoch 200 | Train Loss: 0.3138 | Val Loss 0.2246 | Train R2: 0.6875 | Val R2 0.7718
Epoch 250 | Train Loss: 0.2933 | Val Loss 0.2174 | Train R2: 0.7079 | Val R2 0.7790
Epoch 300 | Train Loss: 0.2897 | Val Loss 0.2171 | Train R2: 0.7114 | Val R2 0.7794
Epoch 350 | Train Loss: 0.2831 | Val Loss 0.2163 | Train R2: 0.7181 | Val R2 0.7802
Epoch 400 | Train Loss: 0.2774 | Val Loss 0.2086 | Train R2: 0.7237 | Val R2 0.7880
Epoch 450 | Train Loss: 0.2733 | Val Loss 0.2144 | Train R2: 0.7278 | Val R2 0.7820
Early stopping at epoch 472
Final val loss: 0.2078
Training model with 10818 params on 11536 samples: 1 to 1.066370863375855 param to data ratio
Epoch 000 | Train Loss: 1.0206 | Val Loss 0.9902 | Train R2: -0.0154 | Val R2 -0.0111
Epoch 050 | Train Loss: 0.6513 | Val Loss 0.5768 | Train R2: 0.3515 | Val R2 0.4131
Epoch 100 | Train Loss: 0.5766 | Val Loss 0.5275 | Train R2: 0.4253 | Val R2 0.4655
Epoch 150 | Train Loss: 0.4280 | Val Loss 0.3267 | Train R2: 0.5738 | Val R2 0.6673
Epoch 200 | Train Loss: 0.3456 | Val Loss 0.2374 | Train R2: 0.6559 | Val R2 0.7585
Epoch 250 | Train Loss: 0.3235 | Val Loss 0.2281 | Train R2: 0.6779 | Val R2 0.7680
Epoch 300 | Train Loss: 0.3213 | Val Loss 0.2438 | Train R2: 0.6801 | Val R2 0.7517
Early stopping at epoch 338
Final val loss: 0.2182
Training model with 10818 params on 11536 samples: 1 to 1.066370863375855 param to data ratio
Epoch 000 | Train Loss: 1.0156 | Val Loss 0.9839 | Train R2: -0.0105 | Val R2 -0.0047
Epoch 050 | Train Loss: 0.6701 | Val Loss 0.6748 | Train R2: 0.3327 | Val R2 0.3133
Epoch 100 | Train Loss: 0.6303 | Val Loss 0.6533 | Train R2: 0.3719 | Val R2 0.3364
Epoch 150 | Train Loss: 0.6143 | Val Loss 0.6125 | Train R2: 0.3879 | Val R2 0.3778
Epoch 200 | Train Loss: 0.5720 | Val Loss 0.5510 | Train R2: 0.4303 | Val R2 0.4386
Epoch 250 | Train Loss: 0.5461 | Val Loss 0.5017 | Train R2: 0.4563 | Val R2 0.4883
Epoch 300 | Train Loss: 0.4974 | Val Loss 0.4053 | Train R2: 0.5048 | Val R2 0.5871
Epoch 350 | Train Loss: 0.4714 | Val Loss 0.3835 | Train R2: 0.5307 | Val R2 0.6093
Epoch 400 | Train Loss: 0.4631 | Val Loss 0.3712 | Train R2: 0.5389 | Val R2 0.6219
Epoch 450 | Train Loss: 0.4501 | Val Loss 0.3490 | Train R2: 0.5519 | Val R2 0.6444