# LSTM

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import root_mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim
import copy
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import mlflow
from torch.utils.data import Dataset, DataLoader
from torch.utils.data import TensorDataset, DataLoader

In [2]:
train_df = pd.read_csv('../train_competition_2026.csv')
train_df['time'] = pd.to_datetime(train_df['time'], format='%Y-%m-%d %H:%M:%S')
train_df.head()

,obs,sub_id,time,num_0,num_1,num_2,cat_0,cat_1,cat_2,cat_3,cat_4,t_0,t_1,t_2,t_3,t_4,y_1,y_2
0,0,0,2068-09-19 23:34:11,1.38,49,7,1,3,1,0,1,105.5,95.0,67.4,36.6,23.2,33.4,107.4
1,0,0,2068-09-19 23:35:11,1.38,49,7,1,3,1,0,1,104.4,95.0,66.4,37.8,22.7,33.4,107.4
2,0,0,2068-09-19 23:36:11,1.38,49,7,1,3,1,0,1,104.0,95.0,65.2,37.0,22.1,33.4,107.4
3,0,0,2068-09-19 23:37:11,1.38,49,7,1,3,1,0,1,102.8,95.0,63.4,35.9,20.7,33.4,107.4
4,0,0,2068-09-19 23:38:11,1.38,49,7,1,3,1,0,1,101.3,95.1,59.1,34.5,18.1,33.4,107.4

In [3]:
# Confirming every obs is 30 units long
counts = train_df['obs'].value_counts()
counts[counts != 30]

Series([], Name: count, dtype: int64)

In [4]:
test_df = pd.read_csv('../test_no_outcome.csv')
test_df['time'] = pd.to_datetime(test_df['time'], format='%Y-%m-%d %H:%M:%S')
test_df.head(3)

,obs,sub_id,time,num_0,num_1,num_2,cat_0,cat_1,cat_2,cat_3,cat_4,t_0,t_1,t_2,t_3,t_4
0,18,1,2134-04-01 22:23:14,-1.0,38,1,1,1,0,0,0,105.4,99.8,50.7,61.4,36.8
1,18,1,2134-04-01 22:24:14,-1.0,38,1,1,1,0,0,0,105.4,99.4,49.4,61.1,36.2
2,18,1,2134-04-01 22:25:14,-1.0,38,1,1,1,0,0,0,104.6,99.0,49.7,61.4,36.6

In [5]:
def prep_data(df, target_cols, drop_cols, seq_length=30):
    exclude = target_cols + drop_cols + ['obs']
    feature_cols = [col for col in df.columns if col not in exclude]
    
    X_list = []
    y_list = []
    
    for _, group in df.groupby('obs'):
        group = group.sort_values('time')
        
        features = group[feature_cols].values
        X_list.append(features)

        targets = group[target_cols].iloc[0].values
        y_list.append(targets)
        
    return np.stack(X_list), np.stack(y_list), feature_cols

In [6]:
def prep_data(df, target_cols, drop_cols, test_size=0.2):
    exclude = target_cols + drop_cols + ['obs']
    feature_cols = [col for col in df.columns if col not in exclude]
    
    continuous_cols = [col for col in feature_cols if col.startswith('num_') or col.startswith('t_')]
    
    unique_obs = df['obs'].unique()
    train_obs, test_obs = train_test_split(unique_obs, test_size=test_size, random_state=42)
    
    train_df = df[df['obs'].isin(train_obs)].copy()
    test_df = df[df['obs'].isin(test_obs)].copy()
    
    x_scaler = StandardScaler()
    y_scaler = StandardScaler()
    
    if continuous_cols:
        train_df[continuous_cols] = x_scaler.fit_transform(train_df[continuous_cols])
        test_df[continuous_cols] = x_scaler.transform(test_df[continuous_cols])
        
    train_df[target_cols] = y_scaler.fit_transform(train_df[target_cols])
    test_df[target_cols] = y_scaler.transform(test_df[target_cols])
    
    def extract_sequences(data):
        X_list, y_list = [], []
        for _, group in data.groupby('obs'):
            group = group.sort_values('time')
            X_list.append(group[feature_cols].values)
            y_list.append(group[target_cols].iloc[0].values)
            
        return np.stack(X_list), np.stack(y_list)
        
    X_train, y_train = extract_sequences(train_df)
    X_test, y_test = extract_sequences(test_df)
    
    return X_train, y_train, X_test, y_test, y_scaler, feature_cols

In [7]:
target_columns = ['y_1', 'y_2']
columns_to_drop = ['time', 'sub_id'] 

X_train, y_train, X_test, y_test, target_scaler, features = prep_data(
    df=train_df, 
    target_cols=target_columns, 
    drop_cols=columns_to_drop
)

X_tensor = torch.tensor(X_train, dtype=torch.float32)
y_tensor = torch.tensor(y_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

print(f"X shape: {X_tensor.shape}")
print(f"y shape: {y_tensor.shape}")

X shape: torch.Size([11536, 30, 13])
y shape: torch.Size([11536, 2])

In [8]:
class HealthSequenceDataset(Dataset):
    def __init__(self, features, targets):
        self.features = torch.tensor(features, dtype=torch.float32)
        self.targets = torch.tensor(targets, dtype=torch.float32)
        
    def __len__(self):
        return len(self.features)
        
    def __getitem__(self, idx):
        return self.features[idx], self.targets[idx]

dataset = HealthSequenceDataset(X_train, y_train)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [9]:
class LSTM(nn.Module):
    def __init__(self, num_features, hidden_size, num_layers, num_targets, dropout):
        super(LSTM, self).__init__()
        
        dropout = dropout if num_layers > 1 else 0.0

        self.lstm = nn.LSTM(
            input_size=num_features, 
            hidden_size=hidden_size, 
            num_layers=num_layers, 
            batch_first=True,
            dropout=dropout
        )
        
        self.fc = nn.Linear(hidden_size, num_targets)
        
    def forward(self, x):
        out, (hn, cn) = self.lstm(x)
        
        final_timestep_out = out[:, -1, :]
        
        predictions = self.fc(final_timestep_out)
        
        return predictions

In [10]:
def calculate_unscaled_rmse(preds, targets, scaler):
    unscaled_preds = scaler.inverse_transform(preds)
    unscaled_targets = scaler.inverse_transform(targets)
    
    rmses = []
    for i in range(unscaled_targets.shape[1]):
        rmse = root_mean_squared_error(unscaled_targets[:, i], unscaled_preds[:, i])
        rmses.append(rmse)
        
    return np.mean(rmses)

In [11]:
def train(X_tensor, y_tensor, X_test_tensor, y_test_tensor, hidden_size, num_layers, weight_decay, dropout, epochs=100, epochs_int=10):
    dataset = TensorDataset(X_tensor, y_tensor)
    dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

    val_dataset = TensorDataset(X_test_tensor, y_test_tensor)
    val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

    model = LSTM(
        num_features=X_tensor.shape[2],
        hidden_size=hidden_size,
        num_layers=num_layers,
        num_targets=y_tensor.shape[1],
        dropout=dropout
    )

    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=weight_decay)

    counter = 0
    patience = 40
    best_val_loss = float('inf')
    best_val_rmse = float('inf')
    best_model = None

    # Train
    for epoch in range(epochs):
        model.train()
        total_loss = 0
        
        all_train_preds = []
        all_train_targets = []
        
        for batch_X, batch_y in dataloader:
            optimizer.zero_grad()
            
            outputs = model(batch_X)
            loss = criterion(outputs, batch_y)
            
            loss.backward()
            optimizer.step()
            
            total_loss += loss.item()
            
            all_train_preds.append(outputs.detach().cpu().numpy())
            all_train_targets.append(batch_y.detach().cpu().numpy())
        
        train_preds_np = np.vstack(all_train_preds)
        train_targets_np = np.vstack(all_train_targets)
        
        train_rmse = calculate_unscaled_rmse(train_preds_np, train_targets_np, target_scaler)
        
        avg_loss = total_loss / len(dataloader)
        
        # Validate
        val_loss = 0.0
        val_preds, val_true = [], []

        with torch.no_grad():
            for xb, yb in val_loader:
                pred = model(xb)
                loss = criterion(pred, yb)
                val_loss += loss.item()
                
                val_preds.append(pred)
                val_true.append(yb)

        val_loss /= len(val_loader)
        
        val_preds_tensor = torch.cat(val_preds)
        val_true_tensor = torch.cat(val_true)
        
        val_preds_np = val_preds_tensor.cpu().numpy()
        val_targets_np = val_true_tensor.cpu().numpy()
        
        val_rmse = calculate_unscaled_rmse(val_preds_np, val_targets_np, target_scaler)
        
        if val_loss < best_val_loss - 1e-4:
            best_model = model.state_dict()
            best_val_loss = val_loss
            best_val_rmse = val_rmse
            counter = 0
        else:
            counter += 1

        if counter >= patience:
            print("Early stopping triggered.")
            break

        if epoch % epochs_int == 0:
            print(f'Epoch {epoch} | Train RMSE {train_rmse:.4f} | Val RMSE {val_rmse:.4f}')
        
    return best_model, best_val_rmse

In [12]:
def run_pipeline(hp):    
    train_df = pd.read_csv('../train_competition_2026.csv')
    train_df['time'] = pd.to_datetime(train_df['time'], format='%Y-%m-%d %H:%M:%S')
    target_columns = ['y_1', 'y_2']
    columns_to_drop = ['time', 'sub_id'] 

    X_train, y_train, X_test, y_test, target_scaler, features = prep_data(
        df=train_df, 
        target_cols=target_columns, 
        drop_cols=columns_to_drop
    )

    X_tensor = torch.tensor(X_train, dtype=torch.float32)
    y_tensor = torch.tensor(y_train, dtype=torch.float32)
    X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
    y_test_tensor = torch.tensor(y_test, dtype=torch.float32)
    
    model, val_rmse = train(
        X_tensor, y_tensor, X_test_tensor, y_test_tensor,
        hp['hidden_size'],
        hp['num_layers'],
        hp['weight_decay'],
        hp['dropout'],
        epochs=100, epochs_int=10
        )
    
    return model, val_rmse

In [13]:
hp = {
    'hidden_size': 16,
    'num_layers': 2,
    'dropout': 0.0,
    'weight_decay': 1e-4,
    'epochs': 500, 
    'epoch_int': 1,
}

run_pipeline(hp)

Epoch 0 | Train RMSE 9.8632 | Val RMSE 7.1649
Epoch 10 | Train RMSE 6.6301 | Val RMSE 6.5942
Epoch 20 | Train RMSE 6.5226 | Val RMSE 6.5970
Epoch 30 | Train RMSE 6.4468 | Val RMSE 6.6123
Epoch 40 | Train RMSE 6.4087 | Val RMSE 6.6411
Epoch 50 | Train RMSE 6.3394 | Val RMSE 6.6475
Early stopping triggered.

(OrderedDict([('lstm.weight_ih_l0',
               tensor([[ 2.2045e-01,  1.5830e-01,  1.2029e-01,  2.8367e-02, -4.4830e-02,
                        -2.5950e-02, -8.7442e-03,  1.4324e-01,  3.3525e-01,  3.9625e-01,
                        -2.4903e-01,  1.0282e-01,  3.9952e-01],
                       [-7.0783e-02,  4.2138e-02, -4.6229e-02,  1.1264e-01,  8.9325e-02,
                         8.7940e-03,  8.5802e-04,  2.8385e-01,  3.8078e-02, -8.0370e-02,
                         2.1141e-01,  2.0622e-01,  2.1598e-01],
                       [ 1.8728e-01, -6.0673e-02, -6.7027e-02,  7.2155e-01,  1.7478e-01,
                         1.7447e-01,  7.5776e-03, -3.7515e-01,  4.2633e-01,  5.7366e-02,
                        -4.3633e-01, -4.3452e-03, -1.3979e-01],
                       [ 3.7412e-01,  6.5601e-01,  1.3710e-01,  5.1337e-01, -7.9262e-03,
                         1.8157e-01, -6.2501e-02, -1.1810e-02, -2.6483e-01, -1.0478e-01,
                         5.0339e-04,  2.1497e-01,  5.0802e-02],
                       [ 3.8886e-01, -1.2781e-01,  4.8848e-02,  2.5020e-01, -2.5570e-01,
                         2.1709e-02,  5.1748e-02, -3.6833e-02, -1.4721e-01, -5.2225e-02,
                         1.3791e-01, -2.9889e-01, -5.3897e-01],
                       [ 3.3250e-02, -5.3619e-02,  1.8148e-01,  1.3520e-01,  1.3691e-01,
                         2.3197e-01,  1.8022e-01, -2.7557e-02, -1.9821e-01,  2.9463e-01,
                        -4.6167e-01,  1.2838e-01, -1.4878e-01],
                       [-6.9640e-04,  9.6332e-02,  6.7942e-02,  5.0763e-02, -2.3168e-02,
                        -4.9353e-02, -1.3914e-02, -9.9836e-02, -3.3731e-01,  3.8450e-02,
                        -2.9805e-01,  8.7172e-02, -3.8013e-01],
                       [-1.2926e-01, -4.0864e-03,  1.6971e-02, -1.4694e-01,  2.7835e-01,
                         1.2209e-02, -1.5587e-02, -2.8049e-02, -8.9352e-02,  7.8689e-02,
                        -9.5308e-02,  2.2349e-01, -2.7388e-02],
                       [-5.2409e-03, -9.8021e-02, -4.5389e-02,  5.5595e-03,  7.3251e-02,
                         1.4169e-01,  1.7748e-01,  1.0268e-01,  6.3781e-02, -2.4395e-01,
                         1.6590e-01, -2.0936e-01, -2.5471e-01],
                       [-1.1793e-01,  1.8963e-01,  2.5198e-01, -2.8573e-01, -1.6492e-01,
                        -1.7734e-01, -1.3226e-01, -2.2075e-01,  1.7274e-01,  3.9599e-02,
                         2.7384e-01,  2.3750e-01, -4.1736e-01],
                       [-6.6341e-02, -1.2244e-01, -1.3855e-01,  1.4336e-01,  1.5635e-01,
                         7.3833e-02,  9.1405e-02,  1.6570e-01, -4.6787e-02, -1.2951e-01,
                         6.7655e-02, -5.6102e-02, -7.0097e-02],
                       [ 7.4038e-02,  6.5054e-02,  7.2199e-02,  2.1481e-02,  1.4995e-01,
                         1.2862e-01,  1.5060e-01, -5.1615e-02, -2.2283e-01, -1.0780e-01,
                        -1.6438e-01, -1.4337e-01, -1.7496e-01],
                       [-1.4524e-04,  1.1127e-01,  3.2956e-01,  1.3525e-01, -2.4583e-01,
                         7.7756e-03,  2.1392e-02, -1.3459e-01,  5.0062e-03, -4.1839e-01,
                        -1.3292e-01, -3.7177e-01,  3.4250e-01],
                       [ 2.1258e-02,  1.0242e-01, -8.8935e-02,  1.1993e-01, -9.4619e-02,
                         1.1353e-01,  8.6224e-02,  1.8237e-01, -1.6440e-01,  2.4261e-01,
                         3.4542e-01,  3.5071e-01,  3.2114e-01],
                       [ 2.1665e-01,  2.2607e-01,  4.3732e-02, -1.3608e-01, -1.8212e-01,
                        -1.1635e-01,  2.6200e-01,  5.4033e-02,  3.7844e-01, -2.8767e-01,
                        -2.5504e-01, -1.2827e-01, -1.1823e-01],
                       [ 1.3938e-01, -1.2602e-01,  7.2210e-02,  2.2007e-01,  3.0084e-02,
                         3.5412e-02, -2.6756e-01,  1.0551e-01, -1.1161e-01, -2.1583e-01,
                         3.2502e-02,  1.5577e-01, -1.5546e-01],
                       [ 2.1543e-01,  1.1305e-01, -1.9196e-01,  1.1543e-01,  2.0159e-01,
                        -9.1474e-02, -2.4639e-01,  5.7923e-02,  4.7949e-01,  2.5141e-01,
                         7.5314e-02,  3.1111e-02,  2.1352e-02],
                       [-2.4080e-01,  3.0571e-02, -4.1452e-02,  2.4163e-02, -1.0363e-01,
                        -1.0271e-01,  1.7111e-01,  4.5588e-01,  1.3257e-01, -3.1629e-02,
                         1.0491e-01,  1.4411e-01,  8.3056e-02],
                       [-8.8874e-02, -1.1987e-01, -1.7411e-01,  3.9522e-01, -9.4140e-02,
                         4.7173e-02, -1.5577e-01, -1.2786e-01,  3.0519e-01, -1.4093e-01,
                         1.0824e-01,  2.0372e-01,  1.5987e-01],
                       [ 2.9337e-01,  3.7929e-01, -6.6256e-02,  4.8646e-01, -1.0956e-01,
                         3.4412e-01,  2.9731e-02,  2.5474e-01, -8.6598e-02, -1.2306e-01,
                         9.6679e-02,  1.9919e-01,  1.5549e-01],
                       [ 2.0715e-01, -4.9309e-02, -8.5283e-02,  6.0776e-02, -4.8947e-02,
                         7.1793e-02,  3.5310e-02, -1.8774e-02, -2.1570e-01,  1.4882e-01,
                         5.1353e-02, -8.5762e-02, -7.4263e-01],
                       [-2.3890e-01,  3.5612e-02, -3.6687e-02,  2.0253e-01,  3.2458e-02,
                         1.2302e-01, -1.5555e-01, -4.1362e-01,  5.7677e-02, -3.5323e-01,
                        -2.0781e-01,  3.1013e-01,  8.2716e-02],
                       [-1.7086e-01, -1.0604e-01, -1.1781e-01,  1.0566e-01, -1.9757e-01,
                        -8.1203e-02,  1.1652e-02,  1.1955e-01, -2.6466e-01, -2.0995e-01,
                        -1.4259e-01,  1.9037e-02, -2.3019e-01],
                       [ 2.2504e-01,  1.7190e-01, -2.3432e-01, -1.8086e-01,  1.5974e-01,
                         1.6439e-02,  7.2505e-02, -2.6745e-02,  2.0515e-01,  1.5528e-01,
                        -1.3881e-01,  2.7350e-01, -4.0842e-02],
                       [ 5.4665e-02, -9.6455e-02,  4.7600e-03,  1.0637e-01,  2.3879e-02,
                        -3.5703e-02,  1.6151e-01, -5.6502e-02,  4.7001e-02,  1.2817e-01,
                        -1.0149e-02,  1.5409e-01, -6.8333e-02],
                       [ 1.9712e-01, -3.7940e-02,  1.4610e-01, -1.7998e-01,  7.0854e-02,
                        -1.9261e-01, -1.6246e-01, -2.3518e-01,  7.1324e-02, -3.0739e-01,
                        -1.4034e-01,  2.1889e-02, -5.4713e-01],
                       [-2.4195e-01, -1.0652e-01, -6.2646e-02,  2.1009e-01,  2.9577e-01,
                         1.2159e-01, -7.4974e-02,  3.6956e-01, -1.2771e-01, -1.9374e-01,
                         2.3683e-01,  3.1959e-02,  3.0834e-02],
                       [-9.4949e-03,  7.7623e-02,  1.1536e-01,  8.3412e-02,  3.3340e-01,
                         3.0704e-01,  1.7826e-01,  3.4234e-02, -3.2481e-01,  1.6821e-01,
                        -6.9124e-02,  1.8783e-02, -1.8824e-02],
                       [ 1.4260e-02,  3.0141e-01, -3.4942e-02,  1.0600e-01,  4.0289e-02,
                         1.7160e-01,  6.8114e-02, -1.3169e-01, -4.7779e-01, -1.0951e-01,
                        -1.6600e-01, -5.1816e-02,  3.1533e-01],
                       [ 4.7353e-01,  6.0660e-02, -2.0578e-01,  5.3082e-02,  1.5189e-01,
                         1.7228e-01,  4.2128e-01,  1.7013e-01,  8.8999e-02, -2.4045e-01,
                        -6.2910e-02,  3.5038e-01,  7.5470e-03],
                       [ 3.1782e-02, -1.6820e-01, -3.7278e-01, -9.9387e-02,  1.7504e-02,
                        -2.0012e-01,  1.2751e-01,  1.0157e-01,  5.9008e-01,  1.3060e-01,
                        -1.6827e-01,  2.6833e-01,  7.5108e-02],
                       [ 3.9262e-01,  1.5460e-01,  4.5892e-01,  2.5641e-01,  9.2158e-03,
                         1.8978e-02, -1.1362e-01,  3.3880e-01,  2.3823e-01, -1.6421e-01,
                         6.0277e-02,  3.1358e-01,  1.0712e-01],
                       [ 2.2045e-02, -1.2627e-01,  6.9903e-02, -3.2530e-02,  9.0674e-02,
                         1.6856e-01,  2.5427e-01,  3.3761e-01,  4.7885e-01, -4.9980e-01,
                        -1.0052e-03, -2.6735e-01,  1.7049e-02],
                       [ 3.3000e-01, -1.5509e-01,  2.3900e-01,  1.0586e-01, -1.7769e-01,
                         5.1272e-01, -2.3275e-01,  3.5054e-01, -8.3607e-03,  2.2755e-02,
                         2.0094e-01, -1.7425e-01,  4.7470e-02],
                       [-2.7534e-01,  6.7998e-02,  2.0496e-02,  2.4518e-02, -6.1388e-02,
                         4.7587e-03, -1.5964e-01,  7.5022e-02,  5.4088e-01, -8.3883e-02,
                         3.1339e-01, -2.5110e-03,  2.3129e-01],
                       [ 2.8685e-01, -1.9538e-01,  9.9824e-02, -2.4170e-01, -8.1963e-02,
                         9.0110e-03,  3.4803e-01, -1.9665e-01,  2.6425e-01,  2.5150e-03,
                        -1.5329e-01, -6.5517e-02,  3.1609e-01],
                       [ 1.5057e-01, -2.0112e-01, -2.6864e-02,  1.1477e-01,  3.7410e-01,
                         3.0301e-01,  2.9253e-01,  3.5022e-01, -2.2704e-03, -1.8689e-01,
                         7.8134e-02,  8.4492e-02, -3.9860e-01],
                       [ 4.6389e-02, -4.9723e-02,  4.1641e-02, -7.9587e-02,  6.2698e-02,
                         8.8942e-02,  4.5893e-02, -1.6552e-03, -1.6713e-01, -1.3151e-01,
                         3.3864e-02, -4.9104e-02,  7.4586e-01],
                       [-1.0045e-01,  1.4250e-01, -5.7044e-03, -2.1317e-01,  1.7217e-01,
                        -1.7841e-02, -7.9663e-02,  1.5715e-01, -3.0688e-01,  6.1374e-03,
                         7.2674e-02,  9.8088e-02, -4.2962e-01],
                       [ 1.2448e-01,  1.3139e-02, -1.4880e-01, -2.1930e-01,  1.4389e-01,
                         1.9947e-01,  2.4775e-01, -8.0926e-02, -3.2573e-01, -1.4634e-01,
                         9.9472e-03, -7.2943e-02, -1.5447e-01],
                       [-4.7545e-02, -4.0992e-02, -1.9534e-02,  1.0569e-01, -6.1927e-02,
                        -8.9282e-02, -4.4750e-02, -2.2941e-03, -5.0745e-01, -6.1311e-03,
                         8.0671e-03,  5.5403e-02,  2.2888e-01],
                       [-2.1342e-01, -2.4753e-01,  1.3608e-01, -4.6829e-01, -2.4643e-01,
                         9.0527e-03, -3.9634e-01, -2.4826e-02,  3.4502e-01, -2.6571e-01,
                         1.9428e-01,  1.0514e-01,  1.9177e-01],
                       [ 5.8123e-02, -7.7478e-03,  2.4425e-01,  1.0373e-01, -1.1593e-01,
                         1.8873e-01, -4.4976e-02, -1.4951e-01, -7.1731e-02, -3.2957e-01,
                        -2.5468e-01, -9.1387e-02,  2.7463e-03],
                       [ 1.5722e-01,  5.1491e-02,  2.2398e-02, -7.4270e-02,  1.9541e-01,
                         2.5718e-01,  4.7664e-02,  2.5286e-01, -1.0520e-03,  2.3451e-01,
                         1.1404e-01,  2.5475e-01,  2.7124e-01],
                       [-4.0839e-03, -1.9329e-02,  3.8022e-02, -8.8357e-03,  9.6333e-02,
                        -8.1403e-02, -7.1386e-02,  2.5619e-03, -3.4771e-01, -4.7239e-02,
                        -3.4790e-01, -2.4680e-01,  5.2871e-01],
                       [ 8.9291e-02,  1.7910e-01, -1.0576e-01, -2.0686e-01,  6.0679e-02,
                        -1.1465e-01,  1.5985e-01,  1.0648e-01,  1.3698e-02, -7.6350e-02,
                         4.0576e-02,  8.2558e-02,  4.0363e-01],
                       [ 2.0044e-01, -1.7797e-01,  3.2075e-01,  1.0130e-01,  4.7838e-01,
                         2.5218e-01,  6.8487e-03,  2.4279e-02,  2.3642e-01,  1.5026e-01,
                        -6.7559e-02,  1.2347e-02, -7.0203e-02],
                       [-6.8638e-02, -4.1970e-01,  1.0412e-02,  8.1078e-02, -1.6821e-01,
                         1.9212e-01, -3.3380e-01,  1.4488e-01, -5.1156e-01,  2.6686e-01,
                         1.2069e-01,  8.0007e-02,  2.1714e-01],
                       [ 5.1738e-02,  4.3247e-02, -1.2966e-01,  1.5861e-01, -1.3727e-01,
                        -6.0655e-02,  9.5102e-02, -2.7012e-01,  6.0976e-01,  1.0021e-01,
                        -2.5537e-01,  1.7828e-01,  4.1753e-01],
                       [-2.1947e-02, -2.0186e-01, -4.1018e-01,  5.6698e-02, -4.1537e-01,
                         8.5427e-03,  1.8401e-01,  3.5458e-01,  5.1587e-01, -1.5409e-01,
                         2.3211e-01,  1.0627e-01,  2.3308e-01],
                       [-6.9260e-03, -8.7271e-03,  1.5474e-01,  1.3656e-01,  2.7158e-01,
                         2.1924e-01,  2.8346e-01,  1.8452e-01,  2.7183e-01, -2.7495e-01,
                         3.0186e-01,  2.0223e-01,  1.8602e-02],
                       [ 4.0101e-01,  2.3849e-01, -3.8033e-01,  4.5796e-01, -1.0935e-01,
                         3.2931e-01,  1.9420e-01,  1.1955e-01,  4.9205e-02,  8.2299e-02,
                         9.5298e-02,  2.5367e-01,  1.8127e-01],
                       [ 1.1191e-01, -1.1599e-02, -1.1973e-01,  2.4605e-01,  1.3352e-01,
                        -2.2540e-01, -1.1656e-01, -1.2210e-01, -3.8219e-01, -2.3546e-01,
                         5.6870e-02, -1.0680e-01, -5.2750e-01],
                       [-1.9547e-01, -3.9248e-01, -1.7172e-01,  3.9500e-01,  6.2136e-03,
                         8.9554e-02,  1.5319e-01,  2.8864e-02,  1.3393e-02, -3.5978e-01,
                        -6.6540e-02,  1.5726e-02, -7.6368e-02],
                       [ 1.7806e-01, -7.9935e-02,  1.3165e-01,  2.3428e-01, -5.5124e-02,
                         7.8289e-02,  1.0939e-01, -3.6682e-02, -2.9056e-01,  2.2851e-01,
                        -3.8332e-01, -2.9187e-01, -6.1528e-01],
                       [-7.8210e-02, -1.5863e-01, -1.9128e-01,  1.7443e-02,  2.4703e-01,
                         1.1282e-01,  6.9880e-02, -7.1485e-02,  2.5448e-01,  2.4978e-01,
                        -2.6758e-01,  2.2948e-01, -1.9640e-01],
                       [ 2.7144e-01,  1.2646e-01,  1.0783e-01,  1.3316e-01,  3.9711e-01,
                         1.3629e-01,  1.4772e-01, -8.5021e-02,  2.6326e-01,  1.6823e-02,
                         4.3046e-02,  2.0980e-01,  1.5235e-02],
                       [ 2.8753e-02,  4.0351e-01,  2.0808e-01,  2.5100e-01,  2.7027e-01,
                        -2.0450e-01, -2.1298e-01, -2.2387e-02,  8.3270e-02, -2.4215e-03,
                        -8.4085e-02, -2.1325e-01, -3.5064e-01],
                       [-1.4440e-01,  4.2564e-02, -2.8935e-01, -1.3929e-02, -3.2323e-01,
                        -1.1013e-01,  1.2181e-01,  5.6148e-02, -1.8280e-01, -1.9755e-01,
                         1.5043e-02,  2.8435e-02,  9.7166e-02],
                       [ 4.7140e-02,  1.9570e-01, -1.0475e-01, -5.0084e-03,  1.2867e-01,
                         1.5521e-01, -1.1015e-01,  4.7425e-02,  4.2406e-01, -2.1822e-01,
                         2.4712e-01,  1.6621e-01,  7.8534e-01],
                       [ 1.5353e-01,  1.4327e-01, -4.9018e-01,  1.0834e-01,  8.7688e-02,
                        -2.2583e-01, -1.0719e-01, -2.0851e-02, -3.3739e-01, -8.3112e-02,
                        -4.2424e-03,  2.0499e-01,  2.5415e-01],
                       [-4.3635e-01,  1.0300e-01,  5.4279e-01, -2.9716e-01, -1.0565e-01,
                         1.2615e-01, -1.6866e-01,  1.6906e-03,  1.9996e-01,  1.4631e-01,
                        -4.7675e-02,  5.0873e-01,  8.8250e-02],
                       [-1.3760e-01, -1.4140e-01, -1.8617e-01,  2.6610e-01,  1.1275e-01,
                        -8.0990e-02, -1.6475e-01,  3.2747e-02,  8.7815e-01, -1.1822e-01,
                         3.5534e-02, -2.3407e-01,  5.2441e-02],
                       [-1.0779e-01, -2.3361e-01,  1.4071e-01,  4.8316e-01,  2.0259e-01,
                         4.3481e-02, -7.2811e-02, -1.7958e-01,  2.0257e-01,  9.2309e-02,
                         1.7837e-01,  3.7608e-01,  1.6085e-01]])),
              ('lstm.weight_hh_l0',
               tensor([[ 1.0728e-01,  6.1645e-02, -1.4236e-01,  ...,  8.6890e-02,
                         6.2140e-02,  1.0418e-01],
                       [ 7.7977e-02,  3.8590e-02,  2.2829e-02,  ..., -5.9104e-02,
                         7.9751e-02,  6.8564e-02],
                       [-1.3002e-01, -2.5985e-01, -8.2922e-02,  ..., -5.3835e-02,
                        -1.2394e-01, -3.1711e-04],
                       ...,
                       [-7.1437e-03,  9.9132e-02, -4.1667e-02,  ..., -2.6302e-02,
                         1.6641e-02,  3.5546e-01],
                       [ 3.9231e-02, -1.8013e-01,  1.5575e-01,  ...,  3.6725e-02,
                         6.2364e-02,  9.8186e-02],
                       [ 9.3090e-02, -6.4285e-02, -1.1616e-01,  ...,  1.1576e-01,
                         4.0751e-02,  3.3716e-02]])),
              ('lstm.bias_ih_l0',
               tensor([-0.1595,  0.1475, -0.1155, -0.2153, -0.0811,  0.2799,  0.0257,  0.0506,
                        0.2667,  0.0151,  0.1206,  0.0137, -0.1080, -0.0053,  0.0993,  0.1224,
                        0.0450,  0.2037,  0.0127,  0.2005, -0.0249, -0.1250,  0.0010, -0.1195,
                       -0.0101, -0.1359,  0.3682, -0.0479,  0.1590,  0.1349,  0.3578,  0.1867,
                        0.2148, -0.0790,  0.1917,  0.0076, -0.0802, -0.1769, -0.0315, -0.1856,
                        0.0477, -0.0454, -0.1293, -0.1462, -0.0896, -0.2626,  0.0924,  0.0582,
                       -0.1244,  0.0825,  0.2807,  0.1078,  0.1118,  0.4197, -0.0794,  0.1256,
                        0.1740,  0.0233,  0.0995,  0.0567,  0.0982,  0.0223,  0.1555,  0.1178])),
              ('lstm.bias_hh_l0',
               tensor([-0.1062,  0.1300,  0.0235, -0.0417, -0.1053,  0.1620,  0.1822, -0.1002,
                        0.2173, -0.1698,  0.1098,  0.1465,  0.0815,  0.0143,  0.0820,  0.0122,
                        0.0296,  0.1813, -0.1467,  0.0557,  0.0552,  0.1519,  0.0466, -0.1067,
                       -0.0960, -0.1684,  0.4279,  0.0676,  0.1072,  0.1924,  0.2406,  0.0214,
                        0.0887, -0.0890, -0.1687, -0.1307, -0.0017, -0.2420, -0.0182,  0.1309,
                        0.1652, -0.0762, -0.1820,  0.1638,  0.1275, -0.2292,  0.1589, -0.0586,
                        0.1259,  0.0890,  0.2510,  0.2153,  0.0863,  0.4419,  0.0233, -0.0260,
                        0.3388,  0.1661,  0.0736, -0.1023,  0.2827,  0.1117,  0.1232,  0.0010])),
              ('lstm.weight_ih_l1',
               tensor([[ 0.1096, -0.2124, -0.2441,  ...,  0.1443,  0.1946,  0.1427],
                       [ 0.1026, -0.2501,  0.0021,  ...,  0.1051,  0.0816, -0.1176],
                       [-0.0687,  0.4814, -0.2951,  ...,  0.4134, -0.3537,  0.1805],
                       ...,
                       [ 0.0758, -0.0447,  0.1404,  ...,  0.2924,  0.2486,  0.1961],
                       [-0.0924, -0.0801,  0.2201,  ...,  0.1733,  0.1959, -0.0265],
                       [ 0.1720, -0.1542, -0.0613,  ..., -0.0155,  0.1228, -0.2086]])),
              ('lstm.weight_hh_l1',
               tensor([[-9.9199e-02, -1.2609e-01, -3.3288e-01,  ...,  2.1369e-01,
                         6.5586e-03,  6.8570e-02],
                       [-2.0257e-02, -1.9816e-01, -5.4131e-02,  ..., -2.7406e-02,
                         2.6493e-02,  1.2038e-01],
                       [-1.4034e-01, -3.6297e-01,  4.0273e-04,  ..., -2.8053e-01,
                         4.2726e-01,  3.5304e-01],
                       ...,
                       [ 6.1457e-02, -1.0070e-01, -2.5163e-01,  ..., -9.2412e-02,
                         1.4929e-01,  8.3330e-02],
                       [ 8.4691e-02,  5.1817e-02, -1.2604e-01,  ...,  2.6655e-01,
                         3.2672e-01, -1.0266e-01],
                       [ 1.0061e-01,  3.1732e-02, -7.9695e-02,  ...,  8.5573e-02,
                        -1.8891e-01,  9.6086e-02]])),
              ('lstm.bias_ih_l1',
               tensor([ 2.4981e-01, -1.2005e-01, -1.5961e-01, -4.5044e-02,  7.8659e-02,
                        4.1536e-02, -1.1255e-01,  1.5552e-01, -6.5805e-02, -2.2536e-01,
                       -5.4249e-03,  3.9691e-04, -1.4256e-01,  2.0177e-01,  1.5231e-01,
                        2.9675e-02, -1.2162e-01, -1.1548e-01,  5.8961e-01, -4.4258e-03,
                        6.6065e-02,  2.2865e-01,  4.8356e-02,  5.7533e-02, -1.7531e-02,
                        2.2285e-01, -7.6550e-02,  1.4679e-01,  3.7430e-01,  3.2874e-02,

In [14]:
def run_with_mlflow(hp):
    run_name = f"lstm_h{hp['hidden_size']}_l{hp['num_layers']}_w{hp['weight_decay']}"
    with mlflow.start_run(run_name=run_name):
        # mlflow.set_tag("grid_search", "agg_stats_mlp")
        mlflow.log_params(hp)
        model, val_rmse = run_pipeline(hp)
        mlflow.log_metric("val_rmse", val_rmse)
        
        return model, val_rmse

if __name__ == '__main__':
    db_path = "/Users/connoryablonski/Dropbox/USF_MSDS/advanced_ml/mlflow.db"
    mlflow.set_tracking_uri(f"sqlite:///{db_path}")
    mlflow.set_experiment("AML_Project_LSTM_Grid_Search")
    
    print(f"Tracking URI: {mlflow.get_tracking_uri()}")
    print(f"Active Experiment: {mlflow.get_experiment_by_name('AML_Project_LSTM_Grid_Search').experiment_id}")

    from itertools import product

    best_score = float("inf")
    
    hidden_sizes = [32, 64, 128, 256]
    num_layers = [2, 4, 6, 8]
    dropouts = [0.0, 0.2, 0.4]
    weight_decays = [1e-5, 1e-4, 1e-3]
    
    best_model = None

    for hs, nl, dr, wd in product(hidden_sizes, num_layers, dropouts, weight_decays):
        
        hp = {
            'hidden_size': hs,
            'num_layers': nl,
            'dropout': dr,
            'weight_decay': wd,
        }
        
        model, score = run_with_mlflow(hp)
        
        if score < best_score:
            best_score = score
            best_hp = hp
            best_model = model

    print(f"Best config: {best_hp}, val_score: {best_score}")

Tracking URI: sqlite:////Users/connoryablonski/Dropbox/USF_MSDS/advanced_ml/mlflow.db
Active Experiment: 3
Epoch 0 | Train RMSE 8.5471 | Val RMSE 6.8777
Epoch 10 | Train RMSE 6.5866 | Val RMSE 6.5803
Epoch 20 | Train RMSE 6.4210 | Val RMSE 6.5579
Epoch 30 | Train RMSE 6.2815 | Val RMSE 6.6497
Epoch 40 | Train RMSE 6.1541 | Val RMSE 6.7070
Epoch 50 | Train RMSE 5.9771 | Val RMSE 6.8094
Early stopping triggered.
Epoch 0 | Train RMSE 8.4618 | Val RMSE 6.8653
Epoch 10 | Train RMSE 6.5852 | Val RMSE 6.6845
Epoch 20 | Train RMSE 6.4718 | Val RMSE 6.5980
Epoch 30 | Train RMSE 6.3511 | Val RMSE 6.6807
Epoch 40 | Train RMSE 6.2553 | Val RMSE 6.6681
Early stopping triggered.
Epoch 0 | Train RMSE 8.6396 | Val RMSE 7.0050
Epoch 10 | Train RMSE 6.6802 | Val RMSE 6.6557
Epoch 20 | Train RMSE 6.6250 | Val RMSE 6.5926
Epoch 30 | Train RMSE 6.5763 | Val RMSE 6.5513
Epoch 40 | Train RMSE 6.5582 | Val RMSE 6.5763

KeyboardInterrupt: