# Simple Neural Network (Multilayer Perceptron)

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim
import copy
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import mlflow

/opt/miniconda3/envs/msds/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
train_df = pd.read_csv('../train_competition_2026.csv')
train_df.head()

,obs,sub_id,time,num_0,num_1,num_2,cat_0,cat_1,cat_2,cat_3,cat_4,t_0,t_1,t_2,t_3,t_4,y_1,y_2
0,0,0,2068-09-19 23:34:11,1.38,49,7,1,3,1,0,1,105.5,95.0,67.4,36.6,23.2,33.4,107.4
1,0,0,2068-09-19 23:35:11,1.38,49,7,1,3,1,0,1,104.4,95.0,66.4,37.8,22.7,33.4,107.4
2,0,0,2068-09-19 23:36:11,1.38,49,7,1,3,1,0,1,104.0,95.0,65.2,37.0,22.1,33.4,107.4
3,0,0,2068-09-19 23:37:11,1.38,49,7,1,3,1,0,1,102.8,95.0,63.4,35.9,20.7,33.4,107.4
4,0,0,2068-09-19 23:38:11,1.38,49,7,1,3,1,0,1,101.3,95.1,59.1,34.5,18.1,33.4,107.4

In [3]:
train_df['time'] = pd.to_datetime(train_df['time'], format='%Y-%m-%d %H:%M:%S')

In [4]:
test_df = pd.read_csv('../test_no_outcome.csv')
test_df.head()

,obs,sub_id,time,num_0,num_1,num_2,cat_0,cat_1,cat_2,cat_3,cat_4,t_0,t_1,t_2,t_3,t_4
0,18,1,2134-04-01 22:23:14,-1.0,38,1,1,1,0,0,0,105.4,99.8,50.7,61.4,36.8
1,18,1,2134-04-01 22:24:14,-1.0,38,1,1,1,0,0,0,105.4,99.4,49.4,61.1,36.2
2,18,1,2134-04-01 22:25:14,-1.0,38,1,1,1,0,0,0,104.6,99.0,49.7,61.4,36.6
3,18,1,2134-04-01 22:26:14,-1.0,38,1,1,1,0,0,0,104.5,99.6,51.7,61.8,37.2
4,18,1,2134-04-01 22:27:14,-1.0,38,1,1,1,0,0,0,104.6,99.5,52.5,61.9,37.5

## MLP with PCA

In [5]:
def flatten_blocks(df, feature_cols):
    X_flat = df.groupby(["obs"])[feature_cols].apply(lambda block: block.values.flatten())
    X_flat = pd.DataFrame(X_flat.tolist(), index=X_flat.index)
    return X_flat.reset_index()

In [6]:
feature_cols = [c for c in train_df.columns if c not in ["sub_id", "obs", "time", "y_1", "y_2"]]

X_train_flat = flatten_blocks(train_df, feature_cols)
X_test_flat  = flatten_blocks(test_df, feature_cols)

In [7]:
X_train_flat.head()

,obs,0,1,2,3,4,5,6,7,8,...,380,381,382,383,384,385,386,387,388,389
0,0,1.38,49.0,7.0,1.0,3.0,1.0,0.0,1.0,105.5,...,1.0,3.0,1.0,0.0,1.0,94.5,93.8,59.8,34.3,17.7
1,1,1.38,49.0,7.0,1.0,3.0,1.0,0.0,1.0,98.6,...,1.0,3.0,1.0,0.0,1.0,95.3,92.9,52.1,38.0,22.0
2,2,1.38,49.0,7.0,1.0,3.0,1.0,0.0,1.0,93.1,...,1.0,3.0,1.0,0.0,1.0,91.2,93.4,52.5,36.1,19.1
3,3,1.38,49.0,7.0,1.0,3.0,1.0,0.0,1.0,85.1,...,1.0,3.0,1.0,0.0,1.0,87.1,95.0,61.8,36.4,20.8
4,4,1.38,49.0,7.0,1.0,3.0,1.0,0.0,1.0,88.7,...,1.0,3.0,1.0,0.0,1.0,86.1,89.6,66.7,32.5,17.8

In [8]:
def extract_targets(df):
    return df.groupby(["obs"])[["y_1", "y_2"]].first().reset_index(drop=True)

y_train = extract_targets(train_df)

In [9]:
class SimpleMLP(nn.Module):
    def __init__(self, input_dim, output_dim, num_layers=1, hidden_size=32, dropout=0.0):
        super().__init__()
        
        layers = []
        
        # Input layer
        layers.append(nn.Linear(input_dim, hidden_size))
        layers.append(nn.ReLU())
        if dropout > 0:
            layers.append(nn.Dropout(dropout))
        
        # Hidden layers
        for _ in range(num_layers - 1):
            layers.append(nn.Linear(hidden_size, hidden_size))
            layers.append(nn.ReLU())
            if dropout > 0:
                layers.append(nn.Dropout(dropout))
        
        # Output layer
        layers.append(nn.Linear(hidden_size, output_dim))
        
        self.model = nn.Sequential(*layers)

    def forward(self, x):
        return self.model(x)

In [10]:
def train_mlp(
    X_train, y_train, X_val, y_val,
    input_dim, output_dim, num_layers=1,
    hidden_size=32, dropout=0.0, weight_decay=1e-4,
    epochs=500, epoch_int=10, patience=20, lr=1e-3,
):
    
    model = SimpleMLP(
        input_dim=input_dim,
        output_dim=output_dim,
        num_layers=num_layers,
        hidden_size=hidden_size,
        dropout=dropout
    ).to("cpu")

    criterion = nn.MSELoss()  # change for classification if needed
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)

    # Convert to tensors
    X_train = torch.tensor(X_train, dtype=torch.float32).to("cpu")
    y_train = torch.tensor(y_train, dtype=torch.float32).to("cpu")
    X_val   = torch.tensor(X_val, dtype=torch.float32).to("cpu")
    y_val   = torch.tensor(y_val, dtype=torch.float32).to("cpu")

    best_val_loss = float("inf")
    best_weights = copy.deepcopy(model.state_dict())
    patience_counter = 0

    for epoch in range(epochs):
        # Train
        model.train()
        optimizer.zero_grad()

        train_pred = model(X_train)
        train_loss = criterion(train_pred, y_train)

        train_loss.backward()
        optimizer.step()

        # Val
        model.eval()
        with torch.no_grad():
            val_pred = model(X_val)
            val_loss = criterion(val_pred, y_val)
            
            # Calc r2
            train_r2 = r2_score(y_train.cpu().numpy(), train_pred.detach().cpu().numpy())
            val_r2 = r2_score(y_val.cpu().numpy(), val_pred.cpu().numpy())

        if epoch % epoch_int == 0:
            print(f'Epoch {epoch:03d} | '
                f'Train Loss: {train_loss.item():.4f} | Val Loss {val_loss.item():.4f} | '
                f'Train R2: {train_r2:.4f} | Val R2 {val_r2:.4f}')

        # Early stopping
        if val_loss.item() < best_val_loss:
            best_val_loss = val_loss.item()
            best_weights = copy.deepcopy(model.state_dict())
            patience_counter = 0
        else:
            patience_counter += 1

        if patience_counter >= patience:
            print(f"Early stopping at epoch {epoch}")
            break

    # Restore best model
    model.load_state_dict(best_weights)
    model.eval()
    with torch.no_grad():
        final_val_pred = model(X_val)
        final_val_loss = criterion(final_val_pred, y_val)

    return model, final_val_loss

In [11]:
def run_pipeline(hp):
    k = hp['pca_k']
    
    scaler_x = StandardScaler()
    X_train_raw = X_train_flat.drop(columns=["obs"])
    
    X_train_scaled = scaler_x.fit_transform(X_train_raw)

    pca = PCA(n_components=k, random_state=42)
    X_train_pca = pca.fit_transform(X_train_scaled)
    
    scaler_y = StandardScaler()
    y_train_scaled = scaler_y.fit_transform(y_train)

    X_train_split, X_val, y_train_split, y_val = train_test_split(
        X_train_pca, y_train_scaled, test_size=0.2, random_state=42
    )

    model, val_loss = train_mlp(
        X_train_split, y_train_split, X_val, y_val,
        input_dim=X_train_split.shape[1],
        output_dim=2,
        num_layers=hp['num_layers'],
        hidden_size=hp['hidden_size'],
        dropout=hp['dropout'],
        weight_decay=hp['weight_decay'],
        epochs=hp['epochs'],
        epoch_int=hp['epoch_int'],
        patience=hp['patience'],
        lr=hp['lr']
    )
    
    return model, val_loss, scaler_x, scaler_y, pca

In [12]:
hp = {
    'pca_k': 50,
    'hidden_size': 64,
    'num_layers': 4,
    'dropout': 0.0,
    'weight_decay': 1e-3,
    'epochs': 10000, 
    'epoch_int': 50,
    'patience': 50,
    'lr': 1e-3
}

model, val_loss, scaler_x, scaler_y, pca = run_pipeline(hp)

Epoch 000 | Train Loss: 1.0171 | Val Loss 0.9767 | Train R2: -0.0119 | Val R2 0.0025
Epoch 050 | Train Loss: 0.2168 | Val Loss 0.2184 | Train R2: 0.7840 | Val R2 0.7780
Epoch 100 | Train Loss: 0.1921 | Val Loss 0.1967 | Train R2: 0.8086 | Val R2 0.8002
Epoch 150 | Train Loss: 0.1846 | Val Loss 0.1946 | Train R2: 0.8160 | Val R2 0.8023
Epoch 200 | Train Loss: 0.1774 | Val Loss 0.1958 | Train R2: 0.8233 | Val R2 0.8010
Early stopping at epoch 201

In [13]:
def get_real_predictions(model, X_test_df, scaler_x, scaler_y, pca):
    X_raw = X_test_df.drop(columns=["obs"]) if "obs" in X_test_df.columns else X_test_df
    X_scaled = scaler_x.transform(X_raw)
    
    X_pca = pca.transform(X_scaled)
    
    model.eval()
    X_tensor = torch.FloatTensor(X_pca)
    
    with torch.no_grad():
        y_pred_tensor = model(X_tensor)

    y_pred_scaled = y_pred_tensor.cpu().numpy()
    y_pred_final = scaler_y.inverse_transform(y_pred_scaled)
    
    return y_pred_final

In [14]:
predictions = get_real_predictions(model, X_test_flat, scaler_x, scaler_y, pca)

y_test_pred = get_real_predictions(model, X_test_flat, scaler_x, scaler_y, pca)

pred_df = pd.concat(
    [
        X_test_flat[["obs"]].reset_index(drop=True), 
        pd.DataFrame(y_test_pred, columns=["y_1", "y_2"])
    ],
    axis=1
)

len(y_test_pred)

3450

In [15]:
pred_df.to_csv("mlp_pca_1.csv", index=False)

In [ ]:
def run_with_mlflow(hp):
    run_name = f"lstm_k{hp['pca_k']}_h{hp['hidden_size']}_l{hp['num_layers']}_d{hp['dropout']}_w{hp['weight_decay']}"
    with mlflow.start_run(run_name=run_name):
        mlflow.set_tag("tuning", "pca_v_hiddensize_2")
        mlflow.log_params(hp)
        model, val_loss, _, _, _ = run_pipeline(hp)
        mlflow.log_metric("val_loss", val_loss)
        
        return model, val_loss

if __name__ == '__main__':
    db_path = "/Users/connoryablonski/Dropbox/USF_MSDS/advanced_ml/mlflow.db"
    mlflow.set_tracking_uri(f"sqlite:///{db_path}")
    mlflow.set_experiment("AML_Project_MLP_Grid_Search")
    
    print(f"Tracking URI: {mlflow.get_tracking_uri()}")
    print(f"Active Experiment: {mlflow.get_experiment_by_name('AML_Project_MLP_Grid_Search').experiment_id}")

    from itertools import product

    best_score = float("inf")
    
    pca_ks = [30, 40, 50, 60, 70, 80, 90, 100]
    hidden_sizes = [16, 32, 64, 128, 256]
    num_layers = [3]
    dropouts = [0.2]
    weight_decays = [1e-3]
    
    best_model = None
    best_pca = None

    for ks, hs, nl, dr, wd in product(pca_ks, hidden_sizes, num_layers, dropouts, weight_decays):
        
        hp = {
            'pca_k': ks,
            'hidden_size': hs,
            'num_layers': nl,
            'dropout': dr,
            'weight_decay': wd,
            'epochs': 10000, 
            'epoch_int': 50,
            'patience': 50,
            'lr': 5e-3
        }
        
        model, score = run_with_mlflow(hp)
        
        if score < best_score:
            best_score = score
            best_hp = hp
            best_model = model
            
            best_pca = PCA(n_components=hp['pca_k'], random_state=42)
            best_pca.fit(X_train_flat.drop(columns=["obs"]))
            

    print("Best:", best_hp, best_score)

Tracking URI: sqlite:////Users/connoryablonski/Dropbox/USF_MSDS/advanced_ml/mlflow.db
Active Experiment: 1
Epoch 000 | Train Loss: 1.2275 | Val Loss 1.1118 | Train R2: -0.2220 | Val R2 -0.1331
Epoch 050 | Train Loss: 0.2142 | Val Loss 0.2138 | Train R2: 0.7866 | Val R2 0.7827
Epoch 100 | Train Loss: 0.1997 | Val Loss 0.2009 | Train R2: 0.8010 | Val R2 0.7958
Epoch 150 | Train Loss: 0.1968 | Val Loss 0.1991 | Train R2: 0.8039 | Val R2 0.7977
Epoch 200 | Train Loss: 0.1952 | Val Loss 0.1981 | Train R2: 0.8055 | Val R2 0.7987
Epoch 250 | Train Loss: 0.1939 | Val Loss 0.1976 | Train R2: 0.8068 | Val R2 0.7992
Epoch 300 | Train Loss: 0.1925 | Val Loss 0.1970 | Train R2: 0.8081 | Val R2 0.7998
Epoch 350 | Train Loss: 0.1913 | Val Loss 0.1963 | Train R2: 0.8094 | Val R2 0.8005
Epoch 400 | Train Loss: 0.1904 | Val Loss 0.1964 | Train R2: 0.8103 | Val R2 0.8004
Early stopping at epoch 405
Epoch 000 | Train Loss: 1.1260 | Val Loss 0.9436 | Train R2: -0.1207 | Val R2 0.0373
Epoch 050 | Train Loss: 0.3286 | Val Loss 0.2228 | Train R2: 0.6728 | Val R2 0.7735
Epoch 100 | Train Loss: 0.3001 | Val Loss 0.2124 | Train R2: 0.7011 | Val R2 0.7841
Epoch 150 | Train Loss: 0.2903 | Val Loss 0.2124 | Train R2: 0.7109 | Val R2 0.7842
Early stopping at epoch 169
Epoch 000 | Train Loss: 1.0090 | Val Loss 0.9291 | Train R2: -0.0037 | Val R2 0.0506
Epoch 050 | Train Loss: 0.2060 | Val Loss 0.2003 | Train R2: 0.7948 | Val R2 0.7965
Epoch 100 | Train Loss: 0.1977 | Val Loss 0.1961 | Train R2: 0.8030 | Val R2 0.8007
Epoch 150 | Train Loss: 0.1952 | Val Loss 0.1960 | Train R2: 0.8055 | Val R2 0.8009
Epoch 200 | Train Loss: 0.1929 | Val Loss 0.1956 | Train R2: 0.8078 | Val R2 0.8012
Epoch 250 | Train Loss: 0.1910 | Val Loss 0.1950 | Train R2: 0.8097 | Val R2 0.8018
Early stopping at epoch 296
Epoch 000 | Train Loss: 1.0591 | Val Loss 0.9799 | Train R2: -0.0538 | Val R2 -0.0003
Epoch 050 | Train Loss: 0.3686 | Val Loss 0.2438 | Train R2: 0.6331 | Val R2 0.7519
Epoch 100 | Train Loss: 0.3249 | Val Loss 0.2276 | Train R2: 0.6764 | Val R2 0.7685
Early stopping at epoch 109
Epoch 000 | Train Loss: 1.0282 | Val Loss 0.9750 | Train R2: -0.0229 | Val R2 0.0041
Epoch 050 | Train Loss: 0.2104 | Val Loss 0.2070 | Train R2: 0.7904 | Val R2 0.7897
Epoch 100 | Train Loss: 0.1971 | Val Loss 0.1962 | Train R2: 0.8036 | Val R2 0.8007
Epoch 150 | Train Loss: 0.1943 | Val Loss 0.1956 | Train R2: 0.8064 | Val R2 0.8012
Early stopping at epoch 191
Epoch 000 | Train Loss: 1.0413 | Val Loss 0.9979 | Train R2: -0.0361 | Val R2 -0.0188
Epoch 050 | Train Loss: 0.4104 | Val Loss 0.2500 | Train R2: 0.5914 | Val R2 0.7457
Epoch 100 | Train Loss: 0.3588 | Val Loss 0.2405 | Train R2: 0.6427 | Val R2 0.7555
Epoch 150 | Train Loss: 0.3403 | Val Loss 0.2386 | Train R2: 0.6612 | Val R2 0.7576
Epoch 200 | Train Loss: 0.3271 | Val Loss 0.2326 | Train R2: 0.6743 | Val R2 0.7636
Early stopping at epoch 224
Epoch 000 | Train Loss: 1.1854 | Val Loss 0.9082 | Train R2: -0.1786 | Val R2 0.0704
Epoch 050 | Train Loss: 0.2012 | Val Loss 0.2033 | Train R2: 0.7995 | Val R2 0.7934
Epoch 100 | Train Loss: 0.1924 | Val Loss 0.2007 | Train R2: 0.8083 | Val R2 0.7961
Epoch 150 | Train Loss: 0.1884 | Val Loss 0.2002 | Train R2: 0.8123 | Val R2 0.7966
Epoch 200 | Train Loss: 0.1847 | Val Loss 0.1998 | Train R2: 0.8159 | Val R2 0.7970
Epoch 250 | Train Loss: 0.1815 | Val Loss 0.1997 | Train R2: 0.8192 | Val R2 0.7971
Early stopping at epoch 297
Epoch 000 | Train Loss: 1.1372 | Val Loss 0.8512 | Train R2: -0.1314 | Val R2 0.1297
Epoch 050 | Train Loss: 0.2632 | Val Loss 0.2040 | Train R2: 0.7378 | Val R2 0.7927
Epoch 100 | Train Loss: 0.2467 | Val Loss 0.2000 | Train R2: 0.7543 | Val R2 0.7967
Epoch 150 | Train Loss: 0.2421 | Val Loss 0.1988 | Train R2: 0.7588 | Val R2 0.7980
Epoch 200 | Train Loss: 0.2381 | Val Loss 0.1983 | Train R2: 0.7629 | Val R2 0.7985
Epoch 250 | Train Loss: 0.2343 | Val Loss 0.2006 | Train R2: 0.7666 | Val R2 0.7961
Early stopping at epoch 256
Epoch 000 | Train Loss: 1.0072 | Val Loss 0.8982 | Train R2: -0.0019 | Val R2 0.0818
Epoch 050 | Train Loss: 0.1988 | Val Loss 0.1988 | Train R2: 0.8019 | Val R2 0.7979
Epoch 100 | Train Loss: 0.1905 | Val Loss 0.1960 | Train R2: 0.8102 | Val R2 0.8009
Epoch 150 | Train Loss: 0.1861 | Val Loss 0.1958 | Train R2: 0.8145 | Val R2 0.8010
Early stopping at epoch 184
Epoch 000 | Train Loss: 1.1395 | Val Loss 0.9936 | Train R2: -0.1339 | Val R2 -0.0143
Epoch 050 | Train Loss: 0.2902 | Val Loss 0.2101 | Train R2: 0.7110 | Val R2 0.7865
Epoch 100 | Train Loss: 0.2692 | Val Loss 0.2044 | Train R2: 0.7319 | Val R2 0.7922
Epoch 150 | Train Loss: 0.2630 | Val Loss 0.2023 | Train R2: 0.7380 | Val R2 0.7944
Epoch 200 | Train Loss: 0.2565 | Val Loss 0.2036 | Train R2: 0.7445 | Val R2 0.7931
Early stopping at epoch 202
Epoch 000 | Train Loss: 0.9946 | Val Loss 0.9259 | Train R2: 0.0105 | Val R2 0.0540
Epoch 050 | Train Loss: 0.2016 | Val Loss 0.2000 | Train R2: 0.7992 | Val R2 0.7968
Epoch 100 | Train Loss: 0.1927 | Val Loss 0.1964 | Train R2: 0.8080 | Val R2 0.8004
Epoch 150 | Train Loss: 0.1873 | Val Loss 0.1962 | Train R2: 0.8133 | Val R2 0.8006
Early stopping at epoch 188
Epoch 000 | Train Loss: 1.0094 | Val Loss 0.9307 | Train R2: -0.0043 | Val R2 0.0495
Epoch 050 | Train Loss: 0.3056 | Val Loss 0.2162 | Train R2: 0.6957 | Val R2 0.7802
Epoch 100 | Train Loss: 0.2828 | Val Loss 0.2135 | Train R2: 0.7183 | Val R2 0.7829
Epoch 150 | Train Loss: 0.2687 | Val Loss 0.2116 | Train R2: 0.7324 | Val R2 0.7848
Early stopping at epoch 190
Epoch 000 | Train Loss: 1.0267 | Val Loss 0.6512 | Train R2: -0.0216 | Val R2 0.3355
Epoch 050 | Train Loss: 0.1941 | Val Loss 0.1977 | Train R2: 0.8066 | Val R2 0.7991
Epoch 100 | Train Loss: 0.1849 | Val Loss 0.1966 | Train R2: 0.8158 | Val R2 0.8003
Epoch 150 | Train Loss: 0.1765 | Val Loss 0.1971 | Train R2: 0.8241 | Val R2 0.7997
Early stopping at epoch 185
Epoch 000 | Train Loss: 1.3752 | Val Loss 0.8860 | Train R2: -0.3681 | Val R2 0.0945
Epoch 050 | Train Loss: 0.2433 | Val Loss 0.2024 | Train R2: 0.7576 | Val R2 0.7943
Epoch 100 | Train Loss: 0.2279 | Val Loss 0.1991 | Train R2: 0.7729 | Val R2 0.7977
Epoch 150 | Train Loss: 0.2205 | Val Loss 0.1974 | Train R2: 0.7803 | Val R2 0.7994
Epoch 200 | Train Loss: 0.2180 | Val Loss 0.1967 | Train R2: 0.7828 | Val R2 0.8001
Epoch 250 | Train Loss: 0.2161 | Val Loss 0.1966 | Train R2: 0.7848 | Val R2 0.8002
Early stopping at epoch 283
Epoch 000 | Train Loss: 1.0680 | Val Loss 0.8577 | Train R2: -0.0627 | Val R2 0.1239
Epoch 050 | Train Loss: 0.1934 | Val Loss 0.1961 | Train R2: 0.8073 | Val R2 0.8007
Epoch 100 | Train Loss: 0.1828 | Val Loss 0.1957 | Train R2: 0.8178 | Val R2 0.8012
Early stopping at epoch 120
Epoch 000 | Train Loss: 1.0391 | Val Loss 0.8331 | Train R2: -0.0339 | Val R2 0.1490
Epoch 050 | Train Loss: 0.2448 | Val Loss 0.2014 | Train R2: 0.7562 | Val R2 0.7954
Epoch 100 | Train Loss: 0.2320 | Val Loss 0.1971 | Train R2: 0.7688 | Val R2 0.7997
Epoch 150 | Train Loss: 0.2261 | Val Loss 0.1961 | Train R2: 0.7748 | Val R2 0.8008
Epoch 200 | Train Loss: 0.2233 | Val Loss 0.1965 | Train R2: 0.7775 | Val R2 0.8004
Early stopping at epoch 229
Epoch 000 | Train Loss: 1.0079 | Val Loss 0.8862 | Train R2: -0.0028 | Val R2 0.0950
Epoch 050 | Train Loss: 0.1953 | Val Loss 0.1971 | Train R2: 0.8054 | Val R2 0.7997
Epoch 100 | Train Loss: 0.1909 | Val Loss 0.1989 | Train R2: 0.8098 | Val R2 0.7979
Early stopping at epoch 144
Epoch 000 | Train Loss: 1.0415 | Val Loss 0.9208 | Train R2: -0.0361 | Val R2 0.0595
Epoch 050 | Train Loss: 0.2596 | Val Loss 0.2083 | Train R2: 0.7415 | Val R2 0.7883
Epoch 100 | Train Loss: 0.2439 | Val Loss 0.2007 | Train R2: 0.7571 | Val R2 0.7960
Epoch 150 | Train Loss: 0.2326 | Val Loss 0.1993 | Train R2: 0.7682 | Val R2 0.7975
Early stopping at epoch 198
Epoch 000 | Train Loss: 1.1179 | Val Loss 0.9514 | Train R2: -0.1121 | Val R2 0.0235
Epoch 050 | Train Loss: 0.1919 | Val Loss 0.1969 | Train R2: 0.8088 | Val R2 0.8000
Epoch 100 | Train Loss: 0.1824 | Val Loss 0.1955 | Train R2: 0.8183 | Val R2 0.8014
Epoch 150 | Train Loss: 0.1743 | Val Loss 0.1953 | Train R2: 0.8263 | Val R2 0.8015
Early stopping at epoch 180
Epoch 000 | Train Loss: 1.1929 | Val Loss 0.6548 | Train R2: -0.1871 | Val R2 0.3332
Epoch 050 | Train Loss: 0.2254 | Val Loss 0.2005 | Train R2: 0.7755 | Val R2 0.7963
Epoch 100 | Train Loss: 0.2102 | Val Loss 0.1970 | Train R2: 0.7906 | Val R2 0.7998
Epoch 150 | Train Loss: 0.2044 | Val Loss 0.1949 | Train R2: 0.7964 | Val R2 0.8019
Epoch 200 | Train Loss: 0.1999 | Val Loss 0.1950 | Train R2: 0.8009 | Val R2 0.8018
Early stopping at epoch 235
Epoch 000 | Train Loss: 0.9517 | Val Loss 0.5312 | Train R2: 0.0531 | Val R2 0.4572
Epoch 050 | Train Loss: 0.1917 | Val Loss 0.1972 | Train R2: 0.8090 | Val R2 0.7996
Epoch 100 | Train Loss: 0.1798 | Val Loss 0.1965 | Train R2: 0.8209 | Val R2 0.8004
Early stopping at epoch 129
Epoch 000 | Train Loss: 1.1128 | Val Loss 0.7744 | Train R2: -0.1075 | Val R2 0.2099
Epoch 050 | Train Loss: 0.2307 | Val Loss 0.1992 | Train R2: 0.7702 | Val R2 0.7975
Epoch 100 | Train Loss: 0.2169 | Val Loss 0.1960 | Train R2: 0.7839 | Val R2 0.8009
Epoch 150 | Train Loss: 0.2088 | Val Loss 0.1963 | Train R2: 0.7920 | Val R2 0.8005
Early stopping at epoch 195
Epoch 000 | Train Loss: 0.9925 | Val Loss 0.7407 | Train R2: 0.0125 | Val R2 0.2420
Epoch 050 | Train Loss: 0.1940 | Val Loss 0.1975 | Train R2: 0.8067 | Val R2 0.7993
Epoch 100 | Train Loss: 0.1837 | Val Loss 0.1958 | Train R2: 0.8170 | Val R2 0.8011
Early stopping at epoch 138
Epoch 000 | Train Loss: 1.0172 | Val Loss 0.7945 | Train R2: -0.0121 | Val R2 0.1881
Epoch 050 | Train Loss: 0.2358 | Val Loss 0.2017 | Train R2: 0.7651 | Val R2 0.7951
Epoch 100 | Train Loss: 0.2191 | Val Loss 0.1947 | Train R2: 0.7817 | Val R2 0.8022
Epoch 150 | Train Loss: 0.2095 | Val Loss 0.1958 | Train R2: 0.7913 | Val R2 0.8010
Early stopping at epoch 157
Epoch 000 | Train Loss: 1.0680 | Val Loss 0.9731 | Train R2: -0.0626 | Val R2 0.0059
Epoch 050 | Train Loss: 0.2064 | Val Loss 0.2047 | Train R2: 0.7944 | Val R2 0.7920
Epoch 100 | Train Loss: 0.1954 | Val Loss 0.1966 | Train R2: 0.8053 | Val R2 0.8003
Epoch 150 | Train Loss: 0.1931 | Val Loss 0.1960 | Train R2: 0.8075 | Val R2 0.8009
Epoch 200 | Train Loss: 0.1918 | Val Loss 0.1957 | Train R2: 0.8088 | Val R2 0.8012
Epoch 250 | Train Loss: 0.1908 | Val Loss 0.1957 | Train R2: 0.8099 | Val R2 0.8012
Early stopping at epoch 266
Epoch 000 | Train Loss: 1.1199 | Val Loss 0.9501 | Train R2: -0.1144 | Val R2 0.0302
Epoch 050 | Train Loss: 0.3135 | Val Loss 0.2166 | Train R2: 0.6877 | Val R2 0.7800
Epoch 100 | Train Loss: 0.2878 | Val Loss 0.2061 | Train R2: 0.7134 | Val R2 0.7906
Epoch 150 | Train Loss: 0.2882 | Val Loss 0.2072 | Train R2: 0.7130 | Val R2 0.7894
Early stopping at epoch 179
Epoch 000 | Train Loss: 1.0206 | Val Loss 0.9499 | Train R2: -0.0154 | Val R2 0.0299
Epoch 050 | Train Loss: 0.2079 | Val Loss 0.2063 | Train R2: 0.7928 | Val R2 0.7904
Epoch 100 | Train Loss: 0.1955 | Val Loss 0.1975 | Train R2: 0.8052 | Val R2 0.7993
Epoch 150 | Train Loss: 0.1926 | Val Loss 0.1967 | Train R2: 0.8081 | Val R2 0.8002
Epoch 200 | Train Loss: 0.1902 | Val Loss 0.1962 | Train R2: 0.8104 | Val R2 0.8007
Early stopping at epoch 233
Epoch 000 | Train Loss: 1.0916 | Val Loss 0.9839 | Train R2: -0.0859 | Val R2 -0.0048
Epoch 050 | Train Loss: 0.3674 | Val Loss 0.2300 | Train R2: 0.6342 | Val R2 0.7663
Epoch 100 | Train Loss: 0.3229 | Val Loss 0.2222 | Train R2: 0.6784 | Val R2 0.7741
Early stopping at epoch 139
Epoch 000 | Train Loss: 1.0282 | Val Loss 0.9852 | Train R2: -0.0229 | Val R2 -0.0063
Epoch 050 | Train Loss: 0.2071 | Val Loss 0.2036 | Train R2: 0.7936 | Val R2 0.7931
Epoch 100 | Train Loss: 0.1941 | Val Loss 0.1958 | Train R2: 0.8066 | Val R2 0.8011
Epoch 150 | Train Loss: 0.1911 | Val Loss 0.1955 | Train R2: 0.8096 | Val R2 0.8014
Early stopping at epoch 180
Epoch 000 | Train Loss: 1.0513 | Val Loss 1.0013 | Train R2: -0.0458 | Val R2 -0.0229
Epoch 050 | Train Loss: 0.4212 | Val Loss 0.2527 | Train R2: 0.5807 | Val R2 0.7429
Epoch 100 | Train Loss: 0.3528 | Val Loss 0.2315 | Train R2: 0.6487 | Val R2 0.7646
Epoch 150 | Train Loss: 0.3419 | Val Loss 0.2317 | Train R2: 0.6595 | Val R2 0.7643
Early stopping at epoch 182
Epoch 000 | Train Loss: 1.5911 | Val Loss 1.2574 | Train R2: -0.5833 | Val R2 -0.2837
Epoch 050 | Train Loss: 0.1989 | Val Loss 0.2023 | Train R2: 0.8019 | Val R2 0.7944
Epoch 100 | Train Loss: 0.1895 | Val Loss 0.1977 | Train R2: 0.8112 | Val R2 0.7991
Epoch 150 | Train Loss: 0.1852 | Val Loss 0.1967 | Train R2: 0.8154 | Val R2 0.8001
Epoch 200 | Train Loss: 0.1820 | Val Loss 0.1963 | Train R2: 0.8186 | Val R2 0.8006
Early stopping at epoch 245
Epoch 000 | Train Loss: 1.2542 | Val Loss 0.9722 | Train R2: -0.2480 | Val R2 0.0081
Epoch 050 | Train Loss: 0.2735 | Val Loss 0.2024 | Train R2: 0.7276 | Val R2 0.7944
Epoch 100 | Train Loss: 0.2463 | Val Loss 0.1996 | Train R2: 0.7546 | Val R2 0.7972
Epoch 150 | Train Loss: 0.2402 | Val Loss 0.1981 | Train R2: 0.7607 | Val R2 0.7987
Epoch 200 | Train Loss: 0.2387 | Val Loss 0.1976 | Train R2: 0.7622 | Val R2 0.7993
Epoch 250 | Train Loss: 0.2380 | Val Loss 0.1976 | Train R2: 0.7630 | Val R2 0.7993
Early stopping at epoch 286
Epoch 000 | Train Loss: 1.0226 | Val Loss 0.9277 | Train R2: -0.0175 | Val R2 0.0527
Epoch 050 | Train Loss: 0.1966 | Val Loss 0.1973 | Train R2: 0.8041 | Val R2 0.7995
Epoch 100 | Train Loss: 0.1889 | Val Loss 0.1941 | Train R2: 0.8118 | Val R2 0.8027
Epoch 150 | Train Loss: 0.1843 | Val Loss 0.1934 | Train R2: 0.8164 | Val R2 0.8035
Early stopping at epoch 199
Epoch 000 | Train Loss: 1.0422 | Val Loss 0.9474 | Train R2: -0.0370 | Val R2 0.0325
Epoch 050 | Train Loss: 0.2808 | Val Loss 0.2060 | Train R2: 0.7203 | Val R2 0.7906
Epoch 100 | Train Loss: 0.2606 | Val Loss 0.2093 | Train R2: 0.7404 | Val R2 0.7873
Early stopping at epoch 111
Epoch 000 | Train Loss: 0.9984 | Val Loss 0.9153 | Train R2: 0.0066 | Val R2 0.0654
Epoch 050 | Train Loss: 0.1986 | Val Loss 0.2004 | Train R2: 0.8021 | Val R2 0.7964
Epoch 100 | Train Loss: 0.1884 | Val Loss 0.1961 | Train R2: 0.8122 | Val R2 0.8007
Epoch 150 | Train Loss: 0.1817 | Val Loss 0.1965 | Train R2: 0.8189 | Val R2 0.8003
Early stopping at epoch 164
Epoch 000 | Train Loss: 1.0133 | Val Loss 0.9589 | Train R2: -0.0082 | Val R2 0.0211
Epoch 050 | Train Loss: 0.2982 | Val Loss 0.2119 | Train R2: 0.7031 | Val R2 0.7846
Epoch 100 | Train Loss: 0.2787 | Val Loss 0.2083 | Train R2: 0.7224 | Val R2 0.7883
Epoch 150 | Train Loss: 0.2653 | Val Loss 0.2118 | Train R2: 0.7357 | Val R2 0.7847
Early stopping at epoch 170
Epoch 000 | Train Loss: 1.1654 | Val Loss 0.8461 | Train R2: -0.1601 | Val R2 0.1365
Epoch 050 | Train Loss: 0.1902 | Val Loss 0.1972 | Train R2: 0.8104 | Val R2 0.7996
Epoch 100 | Train Loss: 0.1814 | Val Loss 0.1950 | Train R2: 0.8193 | Val R2 0.8019
Epoch 150 | Train Loss: 0.1713 | Val Loss 0.1964 | Train R2: 0.8293 | Val R2 0.8005
Early stopping at epoch 153
Epoch 000 | Train Loss: 1.1869 | Val Loss 0.7959 | Train R2: -0.1811 | Val R2 0.1866
Epoch 050 | Train Loss: 0.2332 | Val Loss 0.1982 | Train R2: 0.7677 | Val R2 0.7986
Epoch 100 | Train Loss: 0.2204 | Val Loss 0.1942 | Train R2: 0.7804 | Val R2 0.8026
Epoch 150 | Train Loss: 0.2172 | Val Loss 0.1938 | Train R2: 0.7836 | Val R2 0.8031
Early stopping at epoch 190
Epoch 000 | Train Loss: 1.0319 | Val Loss 0.8438 | Train R2: -0.0269 | Val R2 0.1388
Epoch 050 | Train Loss: 0.1914 | Val Loss 0.1968 | Train R2: 0.8093 | Val R2 0.8001
Epoch 100 | Train Loss: 0.1802 | Val Loss 0.1951 | Train R2: 0.8205 | Val R2 0.8018
Early stopping at epoch 140
Epoch 000 | Train Loss: 1.0231 | Val Loss 0.8137 | Train R2: -0.0180 | Val R2 0.1684
Epoch 050 | Train Loss: 0.2471 | Val Loss 0.1995 | Train R2: 0.7539 | Val R2 0.7973
Epoch 100 | Train Loss: 0.2277 | Val Loss 0.1975 | Train R2: 0.7732 | Val R2 0.7994
Epoch 150 | Train Loss: 0.2204 | Val Loss 0.1968 | Train R2: 0.7805 | Val R2 0.8000
Early stopping at epoch 180
Epoch 000 | Train Loss: 1.0243 | Val Loss 0.8993 | Train R2: -0.0192 | Val R2 0.0814
Epoch 050 | Train Loss: 0.1907 | Val Loss 0.1961 | Train R2: 0.8100 | Val R2 0.8008
Epoch 100 | Train Loss: 0.1787 | Val Loss 0.1953 | Train R2: 0.8220 | Val R2 0.8016
Early stopping at epoch 138
Epoch 000 | Train Loss: 0.9968 | Val Loss 0.8941 | Train R2: 0.0083 | Val R2 0.0865
Epoch 050 | Train Loss: 0.2548 | Val Loss 0.2046 | Train R2: 0.7462 | Val R2 0.7921
Epoch 100 | Train Loss: 0.2368 | Val Loss 0.1969 | Train R2: 0.7641 | Val R2 0.7999
Epoch 150 | Train Loss: 0.2285 | Val Loss 0.1953 | Train R2: 0.7724 | Val R2 0.8015
Early stopping at epoch 189
Epoch 000 | Train Loss: 1.1030 | Val Loss 0.5077 | Train R2: -0.0976 | Val R2 0.4815
Epoch 050 | Train Loss: 0.1868 | Val Loss 0.1943 | Train R2: 0.8139 | Val R2 0.8026
Epoch 100 | Train Loss: 0.1750 | Val Loss 0.1939 | Train R2: 0.8257 | Val R2 0.8030
Early stopping at epoch 135
Epoch 000 | Train Loss: 1.1607 | Val Loss 0.8383 | Train R2: -0.1538 | Val R2 0.1385
Epoch 050 | Train Loss: 0.2223 | Val Loss 0.1970 | Train R2: 0.7786 | Val R2 0.7998
Epoch 100 | Train Loss: 0.2077 | Val Loss 0.1942 | Train R2: 0.7931 | Val R2 0.8027
Epoch 150 | Train Loss: 0.2005 | Val Loss 0.1935 | Train R2: 0.8003 | Val R2 0.8034
Early stopping at epoch 186
Epoch 000 | Train Loss: 1.0340 | Val Loss 0.6791 | Train R2: -0.0288 | Val R2 0.3060
Epoch 050 | Train Loss: 0.1896 | Val Loss 0.1952 | Train R2: 0.8111 | Val R2 0.8017
Epoch 100 | Train Loss: 0.1772 | Val Loss 0.1944 | Train R2: 0.8235 | Val R2 0.8025
Epoch 150 | Train Loss: 0.1585 | Val Loss 0.1988 | Train R2: 0.8421 | Val R2 0.7980
Early stopping at epoch 151
Epoch 000 | Train Loss: 1.0185 | Val Loss 0.6619 | Train R2: -0.0134 | Val R2 0.3239
Epoch 050 | Train Loss: 0.2266 | Val Loss 0.1983 | Train R2: 0.7742 | Val R2 0.7986
Epoch 100 | Train Loss: 0.2107 | Val Loss 0.1943 | Train R2: 0.7901 | Val R2 0.8025
Epoch 150 | Train Loss: 0.2017 | Val Loss 0.1937 | Train R2: 0.7991 | Val R2 0.8031
Early stopping at epoch 197
Epoch 000 | Train Loss: 0.9991 | Val Loss 0.7976 | Train R2: 0.0060 | Val R2 0.1851
Epoch 050 | Train Loss: 0.1934 | Val Loss 0.1963 | Train R2: 0.8072 | Val R2 0.8005
Epoch 100 | Train Loss: 0.1820 | Val Loss 0.1944 | Train R2: 0.8187 | Val R2 0.8025
Epoch 150 | Train Loss: 0.1677 | Val Loss 0.1985 | Train R2: 0.8329 | Val R2 0.7984
Early stopping at epoch 168
Epoch 000 | Train Loss: 1.0159 | Val Loss 0.8225 | Train R2: -0.0107 | Val R2 0.1595
Epoch 050 | Train Loss: 0.2366 | Val Loss 0.1988 | Train R2: 0.7643 | Val R2 0.7980
Epoch 100 | Train Loss: 0.2185 | Val Loss 0.1961 | Train R2: 0.7823 | Val R2 0.8008
Epoch 150 | Train Loss: 0.2087 | Val Loss 0.1940 | Train R2: 0.7921 | Val R2 0.8029
Early stopping at epoch 175
Epoch 000 | Train Loss: 1.1019 | Val Loss 1.0036 | Train R2: -0.0961 | Val R2 -0.0256
Epoch 050 | Train Loss: 0.2063 | Val Loss 0.2081 | Train R2: 0.7945 | Val R2 0.7885
Epoch 100 | Train Loss: 0.1934 | Val Loss 0.1991 | Train R2: 0.8073 | Val R2 0.7978
Epoch 150 | Train Loss: 0.1901 | Val Loss 0.1982 | Train R2: 0.8106 | Val R2 0.7986
Early stopping at epoch 193
Epoch 000 | Train Loss: 1.0901 | Val Loss 0.9177 | Train R2: -0.0848 | Val R2 0.0626
Epoch 050 | Train Loss: 0.3139 | Val Loss 0.2181 | Train R2: 0.6873 | Val R2 0.7784
Epoch 100 | Train Loss: 0.2930 | Val Loss 0.2067 | Train R2: 0.7082 | Val R2 0.7899
Early stopping at epoch 148
Epoch 000 | Train Loss: 1.0675 | Val Loss 0.9942 | Train R2: -0.0621 | Val R2 -0.0152
Epoch 050 | Train Loss: 0.2078 | Val Loss 0.2089 | Train R2: 0.7929 | Val R2 0.7877
Epoch 100 | Train Loss: 0.1943 | Val Loss 0.1990 | Train R2: 0.8064 | Val R2 0.7978
Epoch 150 | Train Loss: 0.1915 | Val Loss 0.1983 | Train R2: 0.8092 | Val R2 0.7986
Epoch 200 | Train Loss: 0.1897 | Val Loss 0.1982 | Train R2: 0.8109 | Val R2 0.7987
Early stopping at epoch 221
Epoch 000 | Train Loss: 1.0208 | Val Loss 0.9440 | Train R2: -0.0157 | Val R2 0.0359
Epoch 050 | Train Loss: 0.3531 | Val Loss 0.2318 | Train R2: 0.6484 | Val R2 0.7643